// src/pages/audit/ComplianceReports.tsx
import { useState, useEffect } from 'react';
import type { FC } from 'react';
import {
  Card,
  Table,
  Button,
  Select,
  DatePicker,
  Space,
  Typography,
  Row,
  Col,
  Statistic,
  Tag,
  Alert,
  Spin,
  message,
} from 'antd';
import {
  DownloadOutlined,
  FileTextOutlined,
  CheckCircleOutlined,
  WarningOutlined,
  ClockCircleOutlined,
} from '@ant-design/icons';
import { ColumnsType } from 'antd/es/table';
import dayjs from 'dayjs';

const { Title, Text } = Typography;
const { RangePicker } = DatePicker;
const { Option } = Select;

interface ComplianceReport {
  id: string;
  title: string;
  type: string;
  status: 'completed' | 'pending' | 'failed';
  created_at: string;
  generated_by: string;
  file_size: string;
}

const ComplianceReports: FC = () => {
  const [loading, setLoading] = useState(false);
  const [reports, setReports] = useState<ComplianceReport[]>([]);
  const [selectedPeriod, setSelectedPeriod] = useState<string>('month');
  const [dateRange, setDateRange] = useState<[dayjs.Dayjs, dayjs.Dayjs]>([
    dayjs().subtract(1, 'month'),
    dayjs()
  ]);

  useEffect(() => {
    fetchReports();
  }, [selectedPeriod, dateRange]);

  const fetchReports = async () => {
    setLoading(true);
    try {
      // Fetch real compliance reports from backend
      const { fetchComplianceData } = await import('@/utils/analytics');
      const complianceData = await fetchComplianceData();
      
      // Convert compliance data to report format
      const realReports: ComplianceReport[] = complianceData.compliance_reports.map((report, index) => ({
        id: `${index + 1}`,
        title: `${report.period} Compliance Report`,
        type: report.period.includes('Month') ? 'Monthly' : 'Quarterly',
        status: 'completed' as const,
        created_at: new Date().toISOString(), // Use current date as creation date
        generated_by: 'System',
        file_size: `${Math.round(report.transactions * 0.001 + 1.5)} MB` // Estimate file size based on transaction count
      }));
      
      // Add current period report
      const currentReport: ComplianceReport = {
        id: `${realReports.length + 1}`,
        title: 'Monthly Compliance Report',
        type: 'Monthly',
        status: 'completed',
        created_at: dayjs().subtract(1, 'day').toISOString(),
        generated_by: 'System',
        file_size: '2.4 MB'
      };
      
      setReports([currentReport, ...realReports]);
    } catch (error) {
      console.error('Failed to fetch compliance reports:', error);
      
      // Fallback to basic data if API fails
      const fallbackReports: ComplianceReport[] = [
        {
          id: '1',
          title: 'System Compliance Report',
          type: 'Monthly',
          status: 'completed',
          created_at: dayjs().subtract(1, 'day').toISOString(),
          generated_by: 'System',
          file_size: 'Calculating...'
        }
      ];
      setReports(fallbackReports);
      message.error('Failed to load compliance reports. Showing basic data.');
    } finally {
      setLoading(false);
    }
  };

  const handleGenerateReport = () => {
    message.info('Report generation functionality will be implemented');
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'completed': return 'green';
      case 'pending': return 'blue';
      case 'failed': return 'red';
      default: return 'default';
    }
  };

  const getStatusIcon = (status: string) => {
    switch (status) {
      case 'completed': return <CheckCircleOutlined />;
      case 'pending': return <ClockCircleOutlined />;
      case 'failed': return <WarningOutlined />;
      default: return null;
    }
  };

  const columns: ColumnsType<ComplianceReport> = [
    {
      title: 'Report Title',
      dataIndex: 'title',
      key: 'title',
      render: (title: string) => (
        <Text strong>{title}</Text>
      ),
    },
    {
      title: 'Type',
      dataIndex: 'type',
      key: 'type',
      render: (type: string) => (
        <Tag color="blue">{type}</Tag>
      ),
    },
    {
      title: 'Status',
      dataIndex: 'status',
      key: 'status',
      render: (status: string) => (
        <Tag color={getStatusColor(status)} icon={getStatusIcon(status)}>
          {status.toUpperCase()}
        </Tag>
      ),
    },
    {
      title: 'Generated By',
      dataIndex: 'generated_by',
      key: 'generated_by',
    },
    {
      title: 'File Size',
      dataIndex: 'file_size',
      key: 'file_size',
    },
    {
      title: 'Created',
      dataIndex: 'created_at',
      key: 'created_at',
      render: (date: string) => (
        <div>
          <div>{dayjs(date).format('MMM DD, YYYY')}</div>
          <Text type="secondary" style={{ fontSize: '12px' }}>
            {dayjs(date).format('HH:mm:ss')}
          </Text>
        </div>
      ),
      sorter: (a, b) => dayjs(a.created_at).unix() - dayjs(b.created_at).unix(),
    },
    {
      title: 'Actions',
      key: 'actions',
      render: (_, record) => (
        <Space>
          <Button
            type="link"
            icon={<DownloadOutlined />}
            disabled={record.status !== 'completed'}
          >
            Download
          </Button>
        </Space>
      ),
    },
  ];

  if (loading) {
    return (
      <div style={{ textAlign: 'center', padding: '50px' }}>
        <Spin size="large" />
        <div style={{ marginTop: 16 }}>Loading compliance reports...</div>
      </div>
    );
  }

  return (
    <div style={{ padding: '24px', fontFamily: 'Rockwell, serif' }}>
      {/* Header */}
      <div style={{ marginBottom: '24px' }}>
        <Title level={2} style={{ fontFamily: 'Rockwell, serif', fontSize: '18px', margin: 0 }}>
          <FileTextOutlined /> Compliance Reports
        </Title>
        <p style={{ color: '#666', margin: '8px 0 0 0', fontSize: '16px' }}>
          Generate and manage compliance reports for audit and regulatory purposes
        </p>
      </div>

      {/* Statistics Cards */}
      <Row gutter={[16, 16]} style={{ marginBottom: '24px' }}>
        <Col xs={24} sm={12} md={6}>
          <Card size="small">
            <Statistic
              title="Total Reports"
              value={reports.length}
              prefix={<FileTextOutlined />}
            />
          </Card>
        </Col>
        <Col xs={24} sm={12} md={6}>
          <Card size="small">
            <Statistic
              title="Completed"
              value={reports.filter(r => r.status === 'completed').length}
              prefix={<CheckCircleOutlined />}
              valueStyle={{ color: '#52c41a' }}
            />
          </Card>
        </Col>
        <Col xs={24} sm={12} md={6}>
          <Card size="small">
            <Statistic
              title="Pending"
              value={reports.filter(r => r.status === 'pending').length}
              prefix={<ClockCircleOutlined />}
              valueStyle={{ color: '#1890ff' }}
            />
          </Card>
        </Col>
        <Col xs={24} sm={12} md={6}>
          <Card size="small">
            <Statistic
              title="Failed"
              value={reports.filter(r => r.status === 'failed').length}
              prefix={<WarningOutlined />}
              valueStyle={{ color: '#ff4d4f' }}
            />
          </Card>
        </Col>
      </Row>

      {/* Filters and Actions */}
      <Card style={{ marginBottom: '16px' }}>
        <Row gutter={[16, 16]} align="middle">
          <Col xs={24} sm={12} md={6}>
            <Select
              style={{ width: '100%' }}
              placeholder="Report Period"
              value={selectedPeriod}
              onChange={setSelectedPeriod}
            >
              <Option value="week">Weekly</Option>
              <Option value="month">Monthly</Option>
              <Option value="quarter">Quarterly</Option>
              <Option value="year">Yearly</Option>
            </Select>
          </Col>
          <Col xs={24} sm={12} md={8}>
            <RangePicker
              style={{ width: '100%' }}
              value={dateRange}
              onChange={setDateRange}
              format="DD/MM/YYYY"
            />
          </Col>
          <Col xs={24} sm={12} md={10}>
            <Space>
              <Button
                type="primary"
                icon={<FileTextOutlined />}
                onClick={handleGenerateReport}
              >
                Generate Report
              </Button>
              <Button
                icon={<DownloadOutlined />}
                onClick={() => message.info('Bulk download functionality will be implemented')}
              >
                Download All
              </Button>
            </Space>
          </Col>
        </Row>
      </Card>

      {/* Alert for pending reports */}
      {reports.some(r => r.status === 'pending') && (
        <Alert
          message="Reports in Progress"
          description="Some reports are currently being generated. Please check back later."
          type="info"
          showIcon
          closable
          style={{ marginBottom: '16px' }}
        />
      )}

      {/* Reports Table */}
      <Card
        title={`Compliance Reports (${reports.length} reports)`}
        extra={
          <Button icon={<FileTextOutlined />} onClick={handleGenerateReport}>
            New Report
          </Button>
        }
      >
        <Table
          columns={columns}
          dataSource={reports}
          rowKey="id"
          loading={loading}
          pagination={{
            total: reports.length,
            pageSize: 10,
            showSizeChanger: true,
            showQuickJumper: true,
            showTotal: (total, range) =>
              `${range[0]}-${range[1]} of ${total} reports`,
          }}
        />
      </Card>
    </div>
  );
};

export default ComplianceReports;