# Generated by Django 5.2 on 2025-07-04 13:18

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiaryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('category_type', models.CharField(choices=[('MP', 'Member of Parliament'), ('ADMIN_STAFF', 'Administration Staff'), ('DRIVER', 'Driver'), ('CONTRACTOR', 'Contractor/Service Provider'), ('OTHER', 'Other Authorized Personnel')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('base_entitlement_litres', models.DecimalField(decimal_places=2, default=0, help_text='Base fuel entitlement in litres per period', max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Beneficiary Category',
                'verbose_name_plural': 'Beneficiary Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('province', models.CharField(max_length=50)),
                ('distance_from_parliament_km', models.DecimalField(decimal_places=2, help_text='Distance from Parliament in kilometers', max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Constituency',
                'verbose_name_plural': 'Constituencies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FuelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('petrol_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('diesel_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('previous_petrol_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('previous_diesel_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_fuel_allocated', models.FloatField(blank=True, null=True)),
                ('total_fuel_used', models.FloatField(blank=True, null=True)),
                ('available_fuel', models.FloatField(blank=True, null=True)),
                ('last_refuel_date', models.DateTimeField(blank=True, null=True)),
                ('daily_usage_trend', models.CharField(blank=True, max_length=10, null=True)),
                ('daily_usage_change', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Fuel Statistic',
                'verbose_name_plural': 'Fuel Statistics',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ParliamentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=200)),
                ('session_type', models.CharField(choices=[('SITTING', 'Parliament Sitting'), ('COMMITTEE', 'Committee Meeting'), ('NATIONAL_EVENT', 'National Event'), ('SPECIAL_SESSION', 'Special Session')], max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('venue', models.CharField(default='Parliament Building', max_length=200)),
                ('fuel_entitlement_litres', models.DecimalField(decimal_places=2, default=0, help_text='Additional fuel entitlement for attending this session', max_digits=8)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Parliament Session',
                'verbose_name_plural': 'Parliament Sessions',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('min_engine_cc', models.IntegerField(help_text='Minimum engine capacity in CC')),
                ('max_engine_cc', models.IntegerField(help_text='Maximum engine capacity in CC')),
                ('fuel_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Multiplier for fuel allocation based on engine size', max_digits=4)),
            ],
            options={
                'verbose_name': 'Vehicle Category',
                'verbose_name_plural': 'Vehicle Categories',
                'ordering': ['min_engine_cc'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('MAIN_CENTER', 'Main Center Officer'), ('SUB_CENTER', 'Sub Center Officer'), ('APPROVER', 'Approver'), ('BENEFICIARY', 'Beneficiary'), ('AUDITOR', 'Auditor'), ('ADMIN', 'System Administrator')], default='BENEFICIARY', max_length=20)),
                ('phone', models.CharField(blank=True, help_text='Phone number for SMS notifications', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Whether the user registration has been approved by an administrator')),
                ('approved_at', models.DateTimeField(blank=True, help_text='Timestamp when the user was approved', null=True)),
                ('registration_justification', models.TextField(blank=True, help_text="User's justification for registration", null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejecting the user registration', null=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Administrator who approved this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_users', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'System User',
                'verbose_name_plural': 'System Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('box_code', models.CharField(help_text='Unique identifier for the box', max_length=50, unique=True)),
                ('first_coupon_number', models.CharField(max_length=50)),
                ('last_coupon_number', models.CharField(max_length=50)),
                ('total_litres', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('received_by', models.ForeignKey(limit_choices_to={'role__in': ['MAIN_CENTER', 'SUB_CENTER']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_boxes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coupon Box',
                'verbose_name_plural': 'Coupon Boxes',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('book_number', models.CharField(max_length=50)),
                ('first_coupon_number', models.CharField(max_length=50)),
                ('last_coupon_number', models.CharField(max_length=50)),
                ('is_assigned', models.BooleanField(default=False)),
                ('initial_coupon_count', models.IntegerField(blank=True, help_text='Initial number of coupons in the book', null=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='fuel.box')),
            ],
            options={
                'verbose_name': 'Coupon Book',
                'verbose_name_plural': 'Coupon Books',
                'ordering': ['book_number'],
                'unique_together': {('box', 'book_number')},
            },
        ),
        migrations.CreateModel(
            name='FuelEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('entitlement_type', models.CharField(choices=[('MONTHLY', 'Monthly Allowance'), ('SESSION', 'Session Attendance'), ('DISTANCE', 'Distance-based'), ('SPECIAL', 'Special Allocation'), ('EMERGENCY', 'Emergency Allocation')], max_length=20)),
                ('litres_entitled', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('litres_allocated', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('is_fulfilled', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('beneficiary', models.ForeignKey(limit_choices_to={'role': 'BENEFICIARY'}, on_delete=django.db.models.deletion.CASCADE, related_name='fuel_entitlements', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_entitlements', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='fuel.parliamentsession')),
            ],
            options={
                'verbose_name': 'Fuel Entitlement',
                'verbose_name_plural': 'Fuel Entitlements',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('coupon_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('serial_number', models.CharField(blank=True, help_text='Unique serial number for the coupon', max_length=50, null=True, unique=True)),
                ('barcode', models.TextField(blank=True, help_text='Barcode data for the coupon (base64 encoded image or text)', null=True)),
                ('qr_code', models.TextField(blank=True, help_text='QR code data for the coupon (base64 encoded image or text)')),
                ('litres', models.DecimalField(decimal_places=2, default=20.0, help_text='Fuel amount in litres (typically 20L)', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ALLOCATED', 'Allocated'), ('USED', 'Used'), ('EXPIRED', 'Expired'), ('DAMAGED', 'Damaged')], db_index=True, default='AVAILABLE', max_length=20)),
                ('allocated_date', models.DateTimeField(blank=True, null=True)),
                ('used_date', models.DateTimeField(blank=True, null=True)),
                ('transaction_location', models.CharField(blank=True, help_text='Location where the coupon was used', max_length=200, null=True)),
                ('expiry_date', models.DateField(blank=True, db_index=True, help_text='Date when the coupon expires', null=True)),
                ('allocated_to', models.ForeignKey(blank=True, limit_choices_to={'role': 'BENEFICIARY'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_coupons', to=settings.AUTH_USER_MODEL)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='fuel.book')),
                ('entitlement', models.ForeignKey(blank=True, help_text='The entitlement this coupon fulfills', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_coupons', to='fuel.fuelentitlement')),
            ],
            options={
                'verbose_name': 'Fuel Coupon',
                'verbose_name_plural': 'Fuel Coupons',
                'ordering': ['coupon_number'],
            },
        ),
        migrations.CreateModel(
            name='FuelTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('litres_consumed', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('transaction_location', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True)),
                ('beneficiary', models.ForeignKey(limit_choices_to={'role': 'BENEFICIARY'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_transactions', to=settings.AUTH_USER_MODEL)),
                ('coupon', models.ForeignKey(blank=True, help_text='Optional: The coupon used for this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_transactions', to='fuel.coupon')),
                ('recorded_by', models.ForeignKey(blank=True, help_text='User who recorded this transaction (e.g., a fuel station attendant or officer)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_fuel_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fuel Transaction',
                'verbose_name_plural': 'Fuel Transactions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Handover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('handover_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Confirmation'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('confirmation_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers', to='fuel.book')),
                ('box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers', to='fuel.box')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers', to='fuel.coupon')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_handovers', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_handovers', to=settings.AUTH_USER_MODEL)),
                ('witness', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['MAIN_CENTER', 'APPROVER', 'SUB_CENTER', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='witnessed_handovers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Handover',
                'verbose_name_plural': 'Handovers',
                'ordering': ['-handover_date'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=200)),
                ('program_type', models.CharField(choices=[('TRAINING', 'Training Program'), ('DISTRIBUTION', 'Distribution Program'), ('MEETING', 'Community Meeting'), ('ACTIVITY', 'General Activity')], default='DISTRIBUTION', max_length=20)),
                ('scheduled_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('organizer', models.ForeignKey(limit_choices_to={'role__in': ['MAIN_CENTER', 'SUB_CENTER']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_programs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('attended', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(limit_choices_to={'role': 'BENEFICIARY'}, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='fuel.program')),
            ],
            options={
                'verbose_name': 'Program Attendance',
                'verbose_name_plural': 'Program Attendances',
            },
        ),
        migrations.CreateModel(
            name='SessionAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('attended', models.BooleanField(default=False)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('fuel_allocated', models.DecimalField(decimal_places=2, default=0, help_text='Fuel allocated for this session attendance', max_digits=8)),
                ('allocation_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('beneficiary', models.ForeignKey(limit_choices_to={'role': 'BENEFICIARY'}, on_delete=django.db.models.deletion.CASCADE, related_name='session_attendances', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_attendances', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='fuel.parliamentsession')),
            ],
            options={
                'verbose_name': 'Session Attendance',
                'verbose_name_plural': 'Session Attendances',
                'ordering': ['-session__start_date'],
            },
        ),
        migrations.CreateModel(
            name='SubCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('code', models.CharField(help_text='Unique code for the sub-center', max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('location', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('managed_by', models.ForeignKey(limit_choices_to={'role__in': ['MAIN_CENTER', 'SUB_CENTER']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_centers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sub Center',
                'verbose_name_plural': 'Sub Centers',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='program',
            name='sub_center',
            field=models.ForeignKey(blank=True, help_text='The sub-center associated with this program (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='fuel.subcenter'),
        ),
        migrations.AddField(
            model_name='box',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boxes', to='fuel.subcenter'),
        ),
        migrations.AddField(
            model_name='user',
            name='sub_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='fuel.subcenter'),
        ),
        migrations.CreateModel(
            name='SubCenterOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_manager', models.BooleanField(default=False, help_text='Designates if this officer is the manager of the sub-center')),
                ('sub_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officers', to='fuel.subcenter')),
                ('user', models.ForeignKey(limit_choices_to={'role__in': ['MAIN_CENTER', 'SUB_CENTER']}, on_delete=django.db.models.deletion.CASCADE, related_name='officer_of', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sub Center Officer',
                'verbose_name_plural': 'Sub Center Officers',
                'ordering': ['sub_center', '-is_manager', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='BeneficiaryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('monthly_entitlement_litres', models.DecimalField(decimal_places=2, default=0, help_text='Monthly fuel entitlement in litres', max_digits=8)),
                ('is_active_beneficiary', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beneficiaries', to='fuel.beneficiarycategory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_profile', to=settings.AUTH_USER_MODEL)),
                ('constituency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiaries', to='fuel.constituency')),
                ('vehicle_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiaries', to='fuel.vehiclecategory')),
            ],
            options={
                'verbose_name': 'Beneficiary Profile',
                'verbose_name_plural': 'Beneficiary Profiles',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='CouponDistribution',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('coupon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='distribution', serialize=False, to='fuel.coupon')),
                ('distribution_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('beneficiary', models.ForeignKey(limit_choices_to={'role': 'BENEFICIARY'}, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_distributions', to=settings.AUTH_USER_MODEL)),
                ('distributed_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['MAIN_CENTER', 'SUB_CENTER']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributed_coupons', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_distributions', to='fuel.program')),
            ],
            options={
                'verbose_name': 'Coupon Distribution',
                'verbose_name_plural': 'Coupon Distributions',
            },
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['status'], name='fuel_coupon_status_5670fa_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['allocated_to'], name='fuel_coupon_allocat_33eb0a_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['book', 'coupon_number'], name='fuel_coupon_book_id_7331c9_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['expiry_date'], name='fuel_coupon_expiry__7d592d_idx'),
        ),
        migrations.AddIndex(
            model_name='fueltransaction',
            index=models.Index(fields=['beneficiary'], name='fuel_fueltr_benefic_3188b7_idx'),
        ),
        migrations.AddIndex(
            model_name='fueltransaction',
            index=models.Index(fields=['coupon'], name='fuel_fueltr_coupon__5d538a_idx'),
        ),
        migrations.AddIndex(
            model_name='fueltransaction',
            index=models.Index(fields=['timestamp'], name='fuel_fueltr_timesta_684595_idx'),
        ),
        migrations.AddIndex(
            model_name='handover',
            index=models.Index(fields=['from_user'], name='fuel_handov_from_us_1af3a4_idx'),
        ),
        migrations.AddIndex(
            model_name='handover',
            index=models.Index(fields=['to_user'], name='fuel_handov_to_user_f93ecd_idx'),
        ),
        migrations.AddIndex(
            model_name='handover',
            index=models.Index(fields=['status'], name='fuel_handov_status_adfb52_idx'),
        ),
        migrations.AddIndex(
            model_name='handover',
            index=models.Index(fields=['handover_date'], name='fuel_handov_handove_e7d83f_idx'),
        ),
        migrations.AddIndex(
            model_name='fuelentitlement',
            index=models.Index(fields=['beneficiary', 'period_start'], name='fuel_fuelen_benefic_182d4a_idx'),
        ),
        migrations.AddIndex(
            model_name='fuelentitlement',
            index=models.Index(fields=['entitlement_type'], name='fuel_fuelen_entitle_a4a47f_idx'),
        ),
        migrations.AddIndex(
            model_name='fuelentitlement',
            index=models.Index(fields=['is_fulfilled'], name='fuel_fuelen_is_fulf_973c35_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['program', 'attended'], name='fuel_attend_program_ee178c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('user', 'program')},
        ),
        migrations.AlterUniqueTogether(
            name='sessionattendance',
            unique_together={('beneficiary', 'session')},
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['program_type'], name='fuel_progra_program_6f4d11_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['scheduled_date'], name='fuel_progra_schedul_c74c2f_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['sub_center'], name='fuel_progra_sub_cen_63cd02_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='fuel_user_role_dcb10f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['sub_center'], name='fuel_user_sub_cen_aaadf6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_approved'], name='fuel_user_is_appr_9dfd28_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subcenterofficer',
            unique_together={('user', 'sub_center')},
        ),
        migrations.AddIndex(
            model_name='coupondistribution',
            index=models.Index(fields=['beneficiary'], name='fuel_coupon_benefic_b0abe0_idx'),
        ),
        migrations.AddIndex(
            model_name='coupondistribution',
            index=models.Index(fields=['program'], name='fuel_coupon_program_38d4c5_idx'),
        ),
        migrations.AddIndex(
            model_name='coupondistribution',
            index=models.Index(fields=['distribution_date'], name='fuel_coupon_distrib_9a3b2b_idx'),
        ),
    ]
