# Generated by Django for backend model enhancements
# This migration adds missing fields required for frontend functionality

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0001_initial'),
    ]

    operations = [
        # Enhance BeneficiaryProfile with vehicle and contact information
        migrations.AddField(
            model_name='beneficiaryprofile',
            name='vehicle_make',
            field=models.CharField(blank=True, help_text='Vehicle manufacturer', max_length=100),
        ),
        migrations.AddField(
            model_name='beneficiaryprofile',
            name='vehicle_model',
            field=models.CharField(blank=True, help_text='Vehicle model', max_length=100),
        ),
        migrations.AddField(
            model_name='beneficiaryprofile',
            name='vehicle_year',
            field=models.IntegerField(blank=True, help_text='Vehicle manufacture year', null=True),
        ),
        migrations.AddField(
            model_name='beneficiaryprofile',
            name='engine_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Engine size in liters', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='beneficiaryprofile',
            name='vehicle_registration',
            field=models.CharField(blank=True, help_text='Vehicle registration number', max_length=50),
        ),
        migrations.AddField(
            model_name='beneficiaryprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=20),
        ),
        migrations.AddField(
            model_name='beneficiaryprofile',
            name='office_location',
            field=models.CharField(blank=True, help_text='Office or workplace location', max_length=200),
        ),
        migrations.AddField(
            model_name='beneficiaryprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, help_text='Emergency contact information', max_length=200),
        ),
        migrations.AddField(
            model_name='beneficiaryprofile',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes or comments'),
        ),
        migrations.AddField(
            model_name='beneficiaryprofile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the beneficiary is currently active'),
        ),

        # Enhance BeneficiaryCategory with allocation multipliers
        migrations.AddField(
            model_name='beneficiarycategory',
            name='base_allocation',
            field=models.IntegerField(default=100, help_text='Base number of coupons per allocation period'),
        ),
        migrations.AddField(
            model_name='beneficiarycategory',
            name='category_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Multiplier based on role/category', max_digits=4),
        ),
        migrations.AddField(
            model_name='beneficiarycategory',
            name='engine_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Additional multiplier for large engines', max_digits=4),
        ),
        migrations.AddField(
            model_name='beneficiarycategory',
            name='priority_level',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'High'), (4, 'Critical')], default=2, help_text='Priority level for allocations'),
        ),

        # Enhance CouponAllocation with session tracking and usage fields
        migrations.AddField(
            model_name='couponallocation',
            name='session_name',
            field=models.CharField(blank=True, help_text='Legislative session or period name', max_length=200),
        ),
        migrations.AddField(
            model_name='couponallocation',
            name='program_name',
            field=models.CharField(blank=True, help_text='Specific program or initiative name', max_length=200),
        ),
        migrations.AddField(
            model_name='couponallocation',
            name='event_name',
            field=models.CharField(blank=True, help_text='Event or occasion for allocation', max_length=200),
        ),
        migrations.AddField(
            model_name='couponallocation',
            name='allocation_type',
            field=models.CharField(choices=[('MONTHLY', 'Monthly Allocation'), ('QUARTERLY', 'Quarterly Allocation'), ('SPECIAL', 'Special Event'), ('EMERGENCY', 'Emergency Allocation'), ('BONUS', 'Bonus Allocation')], default='MONTHLY', max_length=50),
        ),
        migrations.AddField(
            model_name='couponallocation',
            name='total_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total monetary value of allocation', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='couponallocation',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Date when allocation expires', null=True),
        ),
        migrations.AddField(
            model_name='couponallocation',
            name='coupons_used',
            field=models.IntegerField(default=0, help_text='Number of coupons already used'),
        ),
        migrations.AddField(
            model_name='couponallocation',
            name='coupons_remaining',
            field=models.IntegerField(default=0, help_text='Number of coupons still available'),
        ),
    ]
