# Generated by Django 5.2 on 2025-08-10 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0003_fix_coupon_number_fields_blank'),
    ]

    operations = [
    ]
