# Generated by Django 5.2 on 2025-08-10 22:41

from django.db import migrations, models
from django.db import connection


def check_and_add_fields(apps, schema_editor):
    """Conditionally add fields only if they don't exist (for Azure production)"""
    db_alias = schema_editor.connection.alias
    
    # Get table info
    with connection.cursor() as cursor:
        # Check if fields exist in the table
        if db_alias == 'default':
            try:
                # Try to get column info (works for PostgreSQL and SQLite)
                cursor.execute("SELECT column_name FROM information_schema.columns WHERE table_name = 'fuel_box';")
                columns = [row[0] for row in cursor.fetchall()]
            except:
                # Fallback for SQLite
                cursor.execute("PRAGMA table_info(fuel_box);")
                columns = [row[1] for row in cursor.fetchall()]
                
            # Check which fields are missing
            missing_fields = []
            if 'monetary_value_usd' not in columns:
                missing_fields.append('monetary_value_usd')
            if 'fuel_price_per_litre_usd' not in columns:
                missing_fields.append('fuel_price_per_litre_usd') 
            if 'exchange_rate' not in columns:
                missing_fields.append('exchange_rate')
                
            # Only add fields that don't exist
            Box = apps.get_model('fuel', 'Box')
            
            if 'monetary_value_usd' in missing_fields:
                print("Adding monetary_value_usd field...")
                schema_editor.add_field(
                    Box,
                    Box._meta.get_field('monetary_value_usd')
                )
                
            if 'fuel_price_per_litre_usd' in missing_fields:
                print("Adding fuel_price_per_litre_usd field...")
                schema_editor.add_field(
                    Box,
                    Box._meta.get_field('fuel_price_per_litre_usd')
                )
                
            if 'exchange_rate' in missing_fields:
                print("Adding exchange_rate field...")
                schema_editor.add_field(
                    Box,
                    Box._meta.get_field('exchange_rate')
                )


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0003_fix_coupon_number_fields_blank'),
    ]

    operations = [
        # Use RunPython to conditionally add fields
        migrations.RunPython(check_and_add_fields, migrations.RunPython.noop),
        
        # Ensure box_code field is properly configured for Azure
        migrations.AlterField(
            model_name='box',
            name='box_code',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Unique identifier for the box (e.g., FCB-2025-0001)',
                max_length=50,
                unique=True
            ),
        ),
    ]
