# Generated by Django 5.2 on 2025-08-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0005_add_program_model_fixed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='first_coupon_number',
            field=models.CharField(help_text='First coupon number in the box (e.g., PU006GH355101)', max_length=50),
        ),
        migrations.AlterField(
            model_name='box',
            name='last_coupon_number',
            field=models.CharField(help_text='Last coupon number in the box (e.g., PU006GH355200)', max_length=50),
        ),
    ]
