# Generated by Django 4.2 on 2025-07-23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fueltransaction',
            name='bc_transaction_no',
            field=models.CharField(blank=True, help_text='Business Central transaction number', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='fueltransaction',
            name='employee_no',
            field=models.CharField(blank=True, help_text='Employee number from Business Central', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fueltransaction',
            name='fuel_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fuel amount in currency', max_digits=10),
        ),
        migrations.AddField(
            model_name='fueltransaction',
            name='transaction_date',
            field=models.DateField(auto_now_add=True, help_text='Date of the transaction'),
        ),
        migrations.AddField(
            model_name='fueltransaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Transaction approval status', max_length=20),
        ),
        migrations.AddField(
            model_name='fueltransaction',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='User who approved the transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fueltransaction',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When the transaction was approved', null=True),
        ),
        migrations.AddField(
            model_name='fueltransaction',
            name='created_by_bc',
            field=models.BooleanField(default=False, help_text='Whether this transaction was created by Business Central'),
        ),
        migrations.AddIndex(
            model_name='fueltransaction',
            index=models.Index(fields=['bc_transaction_no'], name='fuel_fueltransaction_bc_transaction_no_idx'),
        ),
        migrations.AddIndex(
            model_name='fueltransaction',
            index=models.Index(fields=['status'], name='fuel_fueltransaction_status_idx'),
        ),
        migrations.AddIndex(
            model_name='fueltransaction',
            index=models.Index(fields=['employee_no'], name='fuel_fueltransaction_employee_no_idx'),
        ),
    ]
