# Generated by Django 5.2 on 2025-07-04 11:09

from django.db import migrations


def populate_coupon_codes(apps, schema_editor):
    """Populate existing coupons with serial numbers, barcodes, and QR codes."""
    Coupon = apps.get_model('fuel', 'Coupon')
    
    # Find the highest existing serial number to avoid duplicates
    existing_serial_numbers = Coupon.objects.exclude(serial_number__isnull=True).exclude(serial_number='').values_list('serial_number', flat=True)
    
    max_counter = 0
    for serial in existing_serial_numbers:
        if serial and serial.startswith('FC') and len(serial) == 8:
            try:
                counter = int(serial[2:])
                max_counter = max(max_counter, counter)
            except ValueError:
                continue
    
    counter = max_counter + 1
    
    for coupon in Coupon.objects.filter(serial_number__isnull=True):
        # Generate unique serial number
        serial_number = f"FC{counter:06d}"
        
        # Generate unique QR and barcode data
        qr_data = f"QR{counter:06d}"
        barcode_data = f"BC{counter:06d}"
        
        # Update coupon with unique data
        coupon.serial_number = serial_number
        coupon.qr_code = qr_data
        coupon.barcode = barcode_data
        coupon.save(update_fields=['serial_number', 'qr_code', 'barcode'])
        
        counter += 1


def reverse_populate_coupon_codes(apps, schema_editor):
    """Reverse the data population."""
    Coupon = apps.get_model('fuel', 'Coupon')
    Coupon.objects.all().update(serial_number=None, qr_code=None, barcode=None)


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_coupon_codes, reverse_populate_coupon_codes),
    ]
