# Generated by Django 5.2 on 2025-07-04 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0009_auto_20250704_1309'),
    ]

    operations = [
        # All operations removed as these fields already exist in 0001_initial.py
        # This migration is kept for dependency chain but does nothing
    ]
