# Generated by Django 5.2 on 2025-07-06 02:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0010_auto_20250704_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['box', 'book_number'], 'verbose_name': 'Coupon Book', 'verbose_name_plural': 'Coupon Books'},
        ),
        migrations.RemoveField(
            model_name='fueldata',
            name='diesel_price',
        ),
        migrations.RemoveField(
            model_name='fueldata',
            name='petrol_price',
        ),
        migrations.RemoveField(
            model_name='fueldata',
            name='previous_diesel_price',
        ),
        migrations.RemoveField(
            model_name='fueldata',
            name='previous_petrol_price',
        ),
        migrations.AddField(
            model_name='book',
            name='assigned_date',
            field=models.DateTimeField(blank=True, help_text='When this book was assigned', null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Parliament member this book is assigned to', limit_choices_to={'role': 'BENEFICIARY'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='box',
            name='coupons_per_book',
            field=models.IntegerField(default=10, help_text='Number of coupons per book', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='box',
            name='denomination',
            field=models.IntegerField(choices=[(5, '5 Litres'), (20, '20 Litres'), (50, '50 Litres')], default=20, help_text='Litres per coupon (5L, 20L, or 50L)'),
        ),
        migrations.AddField(
            model_name='box',
            name='fuel_type',
            field=models.CharField(choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel')], default='DIESEL', help_text='Type of fuel this box contains coupons for', max_length=10),
        ),
        migrations.AddField(
            model_name='box',
            name='number_of_books',
            field=models.IntegerField(default=10, help_text='Number of books in this box', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='coupon',
            name='usd_value',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Value of this coupon in USD (calculated from current fuel price)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fueldata',
            name='diesel_price_usd',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Current diesel price in USD per litre', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fueldata',
            name='petrol_price_usd',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Current petrol price in USD per litre', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fueldata',
            name='previous_diesel_price_usd',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Previous diesel price in USD per litre', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fueldata',
            name='previous_petrol_price_usd',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Previous petrol price in USD per litre', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fueldata',
            name='usd_zwl_exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='USD to ZWL exchange rate for reference', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_number',
            field=models.CharField(help_text='Book number within the box (e.g., Book 1, Book 2, etc.)', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='first_coupon_number',
            field=models.CharField(help_text='First coupon number in this book (e.g., PU00GH355101)', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_assigned',
            field=models.BooleanField(default=False, help_text='Whether this book has been assigned to a beneficiary'),
        ),
        migrations.AlterField(
            model_name='book',
            name='last_coupon_number',
            field=models.CharField(help_text='Last coupon number in this book (e.g., PU00GH355110)', max_length=50),
        ),
        migrations.AlterField(
            model_name='box',
            name='box_code',
            field=models.CharField(help_text='Unique identifier for the box (e.g., FCB-2025-0001)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='box',
            name='first_coupon_number',
            field=models.CharField(help_text='First coupon number in the box (e.g., PU00GH355101)', max_length=50),
        ),
        migrations.AlterField(
            model_name='box',
            name='last_coupon_number',
            field=models.CharField(help_text='Last coupon number in the box (e.g., PU00GH355200)', max_length=50),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_number',
            field=models.CharField(db_index=True, help_text='Unique coupon number (e.g., PU00GH355101)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='litres',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='Fuel amount in litres (5L, 20L, or 50L)', max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Additional serial number if different from coupon_number', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='transaction_location',
            field=models.CharField(blank=True, help_text='Service station or location where the coupon was used', max_length=200, null=True),
        ),
    ]
