# Generated by Django 5.2 on 2025-07-06 02:40

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('fuel', '0011_enhanced_coupon_numbering_usd_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='archive_reason',
            field=models.TextField(blank=True, help_text='Reason for archiving this record', null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='When this record was archived', null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='archived_by',
            field=models.ForeignKey(blank=True, help_text='User who archived this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_%(class)s_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this record has been archived'),
        ),
        migrations.AddField(
            model_name='box',
            name='archive_reason',
            field=models.TextField(blank=True, help_text='Reason for archiving this record', null=True),
        ),
        migrations.AddField(
            model_name='box',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='When this record was archived', null=True),
        ),
        migrations.AddField(
            model_name='box',
            name='archived_by',
            field=models.ForeignKey(blank=True, help_text='User who archived this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_%(class)s_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='box',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this record has been archived'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='archive_reason',
            field=models.TextField(blank=True, help_text='Reason for archiving this record', null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='When this record was archived', null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='archived_by',
            field=models.ForeignKey(blank=True, help_text='User who archived this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_%(class)s_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this record has been archived'),
        ),
        migrations.AlterField(
            model_name='beneficiaryprofile',
            name='constituency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='constituency_beneficiaries', to='fuel.constituency'),
        ),
        migrations.AlterField(
            model_name='beneficiaryprofile',
            name='vehicle_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_beneficiaries', to='fuel.vehiclecategory'),
        ),
        migrations.AlterField(
            model_name='box',
            name='denomination',
            field=models.IntegerField(choices=[(5, '5 Litres'), (10, '10 Litres'), (20, '20 Litres'), (50, '50 Litres')], default=20, help_text='Litres per coupon (5L, 20L, or 50L)'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('object_id', models.CharField(help_text='ID of the object that was affected', max_length=255)),
                ('object_repr', models.CharField(blank=True, help_text='String representation of the affected object', max_length=500)),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('ARCHIVED', 'Archived'), ('UNARCHIVED', 'Unarchived'), ('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('VIEW', 'Viewed'), ('EXPORT', 'Exported'), ('IMPORT', 'Imported'), ('APPROVE', 'Approved'), ('REJECT', 'Rejected'), ('ALLOCATE', 'Allocated'), ('USE', 'Used'), ('DISPATCH', 'Dispatched'), ('RECEIVE', 'Received'), ('VERIFY', 'Verified'), ('DAMAGE', 'Marked as Damaged'), ('SYSTEM', 'System Action')], db_index=True, help_text='Action that was performed', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the action')),
                ('changes', models.JSONField(blank=True, default=dict, help_text='JSON representation of changes made')),
                ('user_ip', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string of the browser/client')),
                ('session_key', models.CharField(blank=True, help_text='Session key for tracking user sessions', max_length=40)),
                ('url', models.URLField(blank=True, help_text='URL where the action was performed')),
                ('is_system_action', models.BooleanField(default=False, help_text='Whether this was an automated system action')),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='LOW', help_text='Severity level of the action', max_length=10)),
                ('content_type', models.ForeignKey(help_text='Type of object that was affected', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='fuel_auditl_content_3803c0_idx'), models.Index(fields=['action'], name='fuel_auditl_action_d6f026_idx'), models.Index(fields=['user'], name='fuel_auditl_user_id_44fc3d_idx'), models.Index(fields=['created'], name='fuel_auditl_created_7bb12e_idx'), models.Index(fields=['severity'], name='fuel_auditl_severit_9cec54_idx'), models.Index(fields=['is_system_action'], name='fuel_auditl_is_syst_13a0c0_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(help_text='Alert title', max_length=200)),
                ('message', models.TextField(help_text='Detailed alert message')),
                ('alert_type', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical'), ('SECURITY', 'Security')], db_index=True, default='INFO', max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], db_index=True, default='ACTIVE', max_length=15)),
                ('object_id', models.CharField(blank=True, help_text='Related object ID', max_length=255)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('auto_resolve_at', models.DateTimeField(blank=True, help_text='Automatically resolve this alert at this time', null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, help_text='Related object type', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Alert',
                'verbose_name_plural': 'System Alerts',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['alert_type'], name='fuel_system_alert_t_afeeff_idx'), models.Index(fields=['status'], name='fuel_system_status_2a8454_idx'), models.Index(fields=['created'], name='fuel_system_created_2de175_idx'), models.Index(fields=['auto_resolve_at'], name='fuel_system_auto_re_1fed0f_idx')],
            },
        ),
    ]
