# Generated by Django 5.2 on 2025-07-06 04:24

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0012_add_archiving_support'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fueldata',
            name='usd_zwl_exchange_rate',
        ),
        migrations.AddField(
            model_name='fueldata',
            name='usd_zwg_exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('27.50'), help_text='USD to ZWG exchange rate for reference (2025 rate ~27.50)', max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='BookDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_archived', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been archived')),
                ('archived_at', models.DateTimeField(blank=True, help_text='When this record was archived', null=True)),
                ('archive_reason', models.TextField(blank=True, help_text='Reason for archiving this record', null=True)),
                ('dispatch_code', models.CharField(help_text='Unique dispatch identifier (e.g., DSP-2025-0001)', max_length=50, unique=True)),
                ('dispatch_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expected_delivery_date', models.DateTimeField(blank=True, null=True)),
                ('actual_delivery_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DISPATCHED', 'Dispatched'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('transport_details', models.TextField(blank=True, help_text='Transport method, vehicle details, etc.')),
                ('notes', models.TextField(blank=True)),
                ('archived_by', models.ForeignKey(blank=True, help_text='User who archived this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('books', models.ManyToManyField(help_text='Books being dispatched', related_name='dispatches', to='fuel.book')),
                ('boxes', models.ManyToManyField(blank=True, help_text='Boxes being dispatched (optional)', related_name='dispatches', to='fuel.box')),
                ('dispatched_by', models.ForeignKey(limit_choices_to={'role__in': ['MAIN_CENTER', 'SUB_CENTER']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_books', to=settings.AUTH_USER_MODEL)),
                ('from_center', models.ForeignKey(help_text='Center dispatching the books (usually main center)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_dispatches', to='fuel.subcenter')),
                ('received_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['MAIN_CENTER', 'SUB_CENTER']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_dispatches', to=settings.AUTH_USER_MODEL)),
                ('to_center', models.ForeignKey(help_text='Destination subcenter', on_delete=django.db.models.deletion.CASCADE, related_name='inbound_dispatches', to='fuel.subcenter')),
            ],
            options={
                'verbose_name': 'Book Dispatch',
                'verbose_name_plural': 'Book Dispatches',
                'ordering': ['-dispatch_date'],
                'indexes': [models.Index(fields=['status'], name='fuel_bookdi_status_e0bac1_idx'), models.Index(fields=['dispatch_date'], name='fuel_bookdi_dispatc_4d96ca_idx'), models.Index(fields=['to_center'], name='fuel_bookdi_to_cent_bdc48b_idx')],
            },
        ),
        migrations.CreateModel(
            name='CouponAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_archived', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been archived')),
                ('archived_at', models.DateTimeField(blank=True, help_text='When this record was archived', null=True)),
                ('archive_reason', models.TextField(blank=True, help_text='Reason for archiving this record', null=True)),
                ('allocation_code', models.CharField(help_text='Unique allocation identifier', max_length=50, unique=True)),
                ('allocation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('collection_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ALLOCATED', 'Allocated'), ('COLLECTED', 'Collected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('vehicle_make', models.CharField(help_text='Vehicle make (e.g., Toyota, Honda)', max_length=100)),
                ('vehicle_model', models.CharField(help_text='Vehicle model (e.g., Camry, Civic)', max_length=100)),
                ('vehicle_registration', models.CharField(help_text='Vehicle registration/license plate number', max_length=50)),
                ('vehicle_year', models.IntegerField(blank=True, help_text='Vehicle year of manufacture', null=True)),
                ('engine_capacity', models.DecimalField(blank=True, decimal_places=1, help_text='Engine capacity in litres (e.g., 2.0L)', max_digits=4, null=True)),
                ('fuel_type', models.CharField(choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel')], help_text='Type of fuel vehicle uses', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('allocated_by', models.ForeignKey(limit_choices_to={'role__in': ['MAIN_CENTER', 'SUB_CENTER']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_allocations', to=settings.AUTH_USER_MODEL)),
                ('archived_by', models.ForeignKey(blank=True, help_text='User who archived this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('beneficiary', models.ForeignKey(limit_choices_to={'role': 'BENEFICIARY'}, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_allocations', to=settings.AUTH_USER_MODEL)),
                ('coupons', models.ManyToManyField(related_name='allocations', to='fuel.coupon')),
                ('sub_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_allocations', to='fuel.subcenter')),
            ],
            options={
                'verbose_name': 'Coupon Allocation',
                'verbose_name_plural': 'Coupon Allocations',
                'ordering': ['-allocation_date'],
                'indexes': [models.Index(fields=['status'], name='fuel_coupon_status_943169_idx'), models.Index(fields=['allocation_date'], name='fuel_coupon_allocat_cb00f8_idx'), models.Index(fields=['beneficiary'], name='fuel_coupon_benefic_bd98ce_idx'), models.Index(fields=['sub_center'], name='fuel_coupon_sub_cen_b52418_idx')],
            },
        ),
    ]
