# Generated by Django 5.2 on 2025-07-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0013_remove_fueldata_usd_zwl_exchange_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERUSER', 'Super User (Developer)'), ('ADMIN', 'System Administrator'), ('MAIN_CENTER', 'Main Center Officer'), ('SUB_CENTER', 'Sub Center Officer'), ('BENEFICIARY', 'Beneficiary'), ('AUDITOR', 'Auditor'), ('MAIN_CENTER_APPROVER', 'Main Center Approver'), ('SUB_CENTER_APPROVER', 'Sub Center Approver')], default='BENEFICIARY', max_length=20),
        ),
    ]
