# Generated by Django 5.2 on 2025-07-07 10:07

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0014_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('employee_id', models.CharField(help_text='Unique employee identification number', max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('id_number', models.CharField(help_text='National ID number', max_length=20, unique=True)),
                ('license_number', models.CharField(help_text="Driver's license number", max_length=20, unique=True)),
                ('license_class', models.CharField(choices=[('CLASS_1', 'Class 1 (Motorcycle)'), ('CLASS_2', 'Class 2 (Light Vehicle)'), ('CLASS_3', 'Class 3 (Heavy Vehicle)'), ('CLASS_4', 'Class 4 (Public Service Vehicle)')], default='CLASS_2', max_length=10)),
                ('license_expiry', models.DateField(help_text="Driver's license expiry date")),
                ('phone_number', models.CharField(help_text='Contact phone number', max_length=15)),
                ('email', models.EmailField(blank=True, help_text='Email address (optional)', max_length=254)),
                ('address', models.TextField(help_text='Physical address')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended'), ('ON_LEAVE', 'On Leave')], default='ACTIVE', max_length=20)),
                ('hire_date', models.DateField(help_text='Date when driver was hired')),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
                'ordering': ['assigned_subcenter', 'last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='PoolVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('registration_number', models.CharField(help_text='Vehicle registration/license plate number', max_length=20, unique=True)),
                ('make', models.CharField(help_text='Vehicle manufacturer', max_length=50)),
                ('model', models.CharField(help_text='Vehicle model', max_length=50)),
                ('year', models.IntegerField(help_text='Year of manufacture')),
                ('vehicle_type', models.CharField(choices=[('CAR', 'Car'), ('VAN', 'Van'), ('TRUCK', 'Truck'), ('MOTORCYCLE', 'Motorcycle'), ('PICKUP', 'Pickup Truck')], default='CAR', max_length=20)),
                ('fuel_type', models.CharField(choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel')], default='DIESEL', max_length=10)),
                ('engine_cc', models.IntegerField(blank=True, help_text='Engine capacity in cubic centimeters', null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('MAINTENANCE', 'Under Maintenance'), ('RETIRED', 'Retired'), ('DAMAGED', 'Damaged')], default='ACTIVE', max_length=20)),
                ('current_mileage', models.IntegerField(default=0, help_text='Current odometer reading in kilometers')),
                ('last_service_date', models.DateField(blank=True, help_text='Date of last service/maintenance', null=True)),
                ('next_service_due', models.DateField(blank=True, help_text='Date when next service is due', null=True)),
                ('insurance_expiry', models.DateField(blank=True, help_text='Insurance policy expiry date', null=True)),
            ],
            options={
                'verbose_name': 'Pool Vehicle',
                'verbose_name_plural': 'Pool Vehicles',
                'ordering': ['assigned_subcenter', 'registration_number'],
            },
        ),
        migrations.CreateModel(
            name='VehicleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('assigned_date', models.DateField(help_text='Date when assignment started')),
                ('unassigned_date', models.DateField(blank=True, help_text='Date when assignment ended', null=True)),
                ('is_primary_driver', models.BooleanField(default=False, help_text='Primary driver for this vehicle')),
                ('notes', models.TextField(blank=True, help_text='Any notes about this assignment')),
            ],
            options={
                'verbose_name': 'Vehicle Assignment',
                'verbose_name_plural': 'Vehicle Assignments',
                'ordering': ['-assigned_date'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='sessionattendance',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='sessionattendance',
            name='beneficiary',
        ),
        migrations.RemoveField(
            model_name='sessionattendance',
            name='recorded_by',
        ),
        migrations.RemoveField(
            model_name='sessionattendance',
            name='session',
        ),
        migrations.AlterModelOptions(
            name='fuelentitlement',
            options={'ordering': ['-created'], 'verbose_name': 'Fuel Entitlement', 'verbose_name_plural': 'Fuel Entitlements'},
        ),
        migrations.RemoveIndex(
            model_name='bookdispatch',
            name='fuel_bookdi_status_e0bac1_idx',
        ),
        migrations.RemoveIndex(
            model_name='bookdispatch',
            name='fuel_bookdi_dispatc_4d96ca_idx',
        ),
        migrations.RemoveIndex(
            model_name='bookdispatch',
            name='fuel_bookdi_to_cent_bdc48b_idx',
        ),
        migrations.RemoveIndex(
            model_name='couponallocation',
            name='fuel_coupon_status_943169_idx',
        ),
        migrations.RemoveIndex(
            model_name='couponallocation',
            name='fuel_coupon_allocat_cb00f8_idx',
        ),
        migrations.RemoveIndex(
            model_name='couponallocation',
            name='fuel_coupon_benefic_bd98ce_idx',
        ),
        migrations.RemoveIndex(
            model_name='couponallocation',
            name='fuel_coupon_sub_cen_b52418_idx',
        ),
        migrations.RemoveIndex(
            model_name='fuelentitlement',
            name='fuel_fuelen_benefic_182d4a_idx',
        ),
        migrations.RemoveIndex(
            model_name='fuelentitlement',
            name='fuel_fuelen_entitle_a4a47f_idx',
        ),
        migrations.RemoveIndex(
            model_name='fuelentitlement',
            name='fuel_fuelen_is_fulf_973c35_idx',
        ),
        migrations.RenameField(
            model_name='bookdispatch',
            old_name='actual_delivery_date',
            new_name='received_date',
        ),
        migrations.RemoveField(
            model_name='bookdispatch',
            name='archive_reason',
        ),
        migrations.RemoveField(
            model_name='bookdispatch',
            name='archived_at',
        ),
        migrations.RemoveField(
            model_name='bookdispatch',
            name='archived_by',
        ),
        migrations.RemoveField(
            model_name='bookdispatch',
            name='boxes',
        ),
        migrations.RemoveField(
            model_name='bookdispatch',
            name='dispatch_code',
        ),
        migrations.RemoveField(
            model_name='bookdispatch',
            name='expected_delivery_date',
        ),
        migrations.RemoveField(
            model_name='bookdispatch',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='bookdispatch',
            name='transport_details',
        ),
        migrations.RemoveField(
            model_name='couponallocation',
            name='allocation_code',
        ),
        migrations.RemoveField(
            model_name='couponallocation',
            name='archive_reason',
        ),
        migrations.RemoveField(
            model_name='couponallocation',
            name='archived_at',
        ),
        migrations.RemoveField(
            model_name='couponallocation',
            name='archived_by',
        ),
        migrations.RemoveField(
            model_name='couponallocation',
            name='collection_date',
        ),
        migrations.RemoveField(
            model_name='couponallocation',
            name='engine_capacity',
        ),
        migrations.RemoveField(
            model_name='couponallocation',
            name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='couponallocation',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='couponallocation',
            name='vehicle_make',
        ),
        migrations.RemoveField(
            model_name='couponallocation',
            name='vehicle_model',
        ),
        migrations.RemoveField(
            model_name='couponallocation',
            name='vehicle_registration',
        ),
        migrations.RemoveField(
            model_name='couponallocation',
            name='vehicle_year',
        ),
        migrations.RemoveField(
            model_name='fuelentitlement',
            name='is_fulfilled',
        ),
        migrations.AddField(
            model_name='fuelentitlement',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='User who approved this entitlement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entitlements_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fuelentitlement',
            name='approved_date',
            field=models.DateTimeField(blank=True, help_text='Date when entitlement was approved', null=True),
        ),
        migrations.AddField(
            model_name='fuelentitlement',
            name='justification',
            field=models.TextField(default=django.utils.timezone.now, help_text='Justification for this entitlement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fuelentitlement',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('ALLOCATED', 'Allocated'), ('PARTIALLY_ALLOCATED', 'Partially Allocated'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='parliamentsession',
            name='managing_subcenter',
            field=models.ForeignKey(blank=True, help_text='SubCenter responsible for managing this session (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_parliament_sessions', to='fuel.subcenter'),
        ),
        migrations.AddField(
            model_name='parliamentsession',
            name='session_manager',
            field=models.ForeignKey(blank=True, help_text='Officer responsible for managing this parliament session', limit_choices_to={'role__in': ['MAIN_CENTER', 'SUB_CENTER']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_parliament_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookdispatch',
            name='books',
            field=models.ManyToManyField(help_text='Books included in this dispatch', related_name='dispatches', to='fuel.book'),
        ),
        migrations.AlterField(
            model_name='bookdispatch',
            name='dispatch_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bookdispatch',
            name='dispatched_by',
            field=models.ForeignKey(help_text='User who dispatched the books', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookdispatch',
            name='from_center',
            field=models.ForeignKey(blank=True, help_text='Source subcenter (null for main center)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatches_sent', to='fuel.subcenter'),
        ),
        migrations.AlterField(
            model_name='bookdispatch',
            name='received_by',
            field=models.ForeignKey(blank=True, help_text='User who received the books', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookdispatch',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DISPATCHED', 'Dispatched'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='bookdispatch',
            name='to_center',
            field=models.ForeignKey(help_text='Destination subcenter', on_delete=django.db.models.deletion.CASCADE, related_name='dispatches_received', to='fuel.subcenter'),
        ),
        migrations.AlterField(
            model_name='couponallocation',
            name='allocated_by',
            field=models.ForeignKey(help_text='User who made the allocation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='couponallocation',
            name='allocation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='couponallocation',
            name='beneficiary',
            field=models.ForeignKey(help_text='Beneficiary receiving the coupons', limit_choices_to={'role': 'BENEFICIARY'}, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_allocations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='couponallocation',
            name='coupons',
            field=models.ManyToManyField(help_text='Coupons included in this allocation', related_name='allocations', to='fuel.coupon'),
        ),
        migrations.AlterField(
            model_name='couponallocation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ALLOCATED', 'Allocated'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='couponallocation',
            name='sub_center',
            field=models.ForeignKey(help_text='Subcenter managing this allocation', on_delete=django.db.models.deletion.CASCADE, related_name='coupon_allocations', to='fuel.subcenter'),
        ),
        migrations.AlterField(
            model_name='fuelentitlement',
            name='beneficiary',
            field=models.ForeignKey(help_text='Parliament member or staff entitled to fuel', limit_choices_to={'role': 'BENEFICIARY'}, on_delete=django.db.models.deletion.CASCADE, related_name='fuel_entitlements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fuelentitlement',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this entitlement record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entitlements_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fuelentitlement',
            name='entitlement_type',
            field=models.CharField(choices=[('MONTHLY', 'Monthly Entitlement'), ('SESSION', 'Parliament Session'), ('COMMITTEE', 'Committee Meeting'), ('SPECIAL_EVENT', 'Special Event'), ('TRAVEL_ALLOWANCE', 'Travel Allowance'), ('EMERGENCY', 'Emergency Allocation'), ('CONSTITUENCY_WORK', 'Constituency Work')], help_text='Type of entitlement', max_length=20),
        ),
        migrations.AlterField(
            model_name='fuelentitlement',
            name='litres_allocated',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount of fuel actually allocated/given', max_digits=8),
        ),
        migrations.AlterField(
            model_name='fuelentitlement',
            name='litres_entitled',
            field=models.DecimalField(decimal_places=2, help_text='Amount of fuel entitled in litres', max_digits=8),
        ),
        migrations.AlterField(
            model_name='fuelentitlement',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about this entitlement'),
        ),
        migrations.AlterField(
            model_name='fuelentitlement',
            name='period_end',
            field=models.DateField(help_text='End date of entitlement period'),
        ),
        migrations.AlterField(
            model_name='fuelentitlement',
            name='period_start',
            field=models.DateField(help_text='Start date of entitlement period'),
        ),
        migrations.AlterField(
            model_name='fuelentitlement',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Related parliament session (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_entitlements', to='fuel.parliamentsession'),
        ),
        migrations.AddIndex(
            model_name='fuelentitlement',
            index=models.Index(fields=['beneficiary', 'period_start', 'period_end'], name='fuel_fuelen_benefic_754450_idx'),
        ),
        migrations.AddIndex(
            model_name='fuelentitlement',
            index=models.Index(fields=['status', 'entitlement_type'], name='fuel_fuelen_status_118613_idx'),
        ),
        migrations.AddIndex(
            model_name='fuelentitlement',
            index=models.Index(fields=['session'], name='fuel_fuelen_session_a69fd5_idx'),
        ),
        migrations.AddField(
            model_name='driver',
            name='assigned_subcenter',
            field=models.ForeignKey(help_text='SubCenter this driver is assigned to', on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='fuel.subcenter'),
        ),
        migrations.AddField(
            model_name='poolvehicle',
            name='assigned_subcenter',
            field=models.ForeignKey(help_text='SubCenter this vehicle is assigned to', on_delete=django.db.models.deletion.CASCADE, related_name='pool_vehicles', to='fuel.subcenter'),
        ),
        migrations.AddField(
            model_name='vehicleassignment',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_assignments', to='fuel.driver'),
        ),
        migrations.AddField(
            model_name='vehicleassignment',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='fuel.poolvehicle'),
        ),
        migrations.DeleteModel(
            name='SessionAttendance',
        ),
        migrations.AddConstraint(
            model_name='vehicleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('unassigned_date__isnull', True)), fields=('vehicle', 'driver'), name='unique_active_assignment'),
        ),
    ]
