# Generated by Django 5.2 on 2025-07-07 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0015_driver_poolvehicle_vehicleassignment_and_more'),
    ]

    operations = [
        # Delete the Handover model completely
        migrations.DeleteModel(
            name='Handover',
        ),
        
        # Fix CouponDistribution table by recreating it with proper primary key
        migrations.RunSQL(
            "DROP TABLE IF EXISTS fuel_coupondistribution_new;",
            reverse_sql="-- No reverse operation"
        ),
        
        migrations.RunSQL(
            """
            CREATE TABLE fuel_coupondistribution_new (
                id BIGSERIAL PRIMARY KEY,
                created timestamptz NOT NULL,
                modified timestamptz NOT NULL,
                coupon_id bigint NOT NULL REFERENCES fuel_coupon(id),
                beneficiary_id bigint NOT NULL REFERENCES fuel_user(id),
                program_id bigint REFERENCES fuel_program(id),
                distributed_by_id bigint REFERENCES fuel_user(id),
                distribution_date timestamptz NOT NULL,
                notes text NOT NULL DEFAULT ''
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS fuel_coupondistribution_new;"
        ),
        
        migrations.RunSQL(
            """
            INSERT INTO fuel_coupondistribution_new (
                created, modified, coupon_id, beneficiary_id, program_id, 
                distributed_by_id, distribution_date, notes
            )
            SELECT 
                created, modified, coupon_id, beneficiary_id, program_id,
                distributed_by_id, distribution_date, notes
            FROM fuel_coupondistribution;
            """,
            reverse_sql="-- No reverse operation"
        ),
        
        migrations.RunSQL(
            "DROP TABLE fuel_coupondistribution;",
            reverse_sql="-- No reverse operation"
        ),
        
        migrations.RunSQL(
            "ALTER TABLE fuel_coupondistribution_new RENAME TO fuel_coupondistribution;",
            reverse_sql="-- No reverse operation"
        ),
        
        # Recreate indexes
        migrations.RunSQL(
            """
            CREATE INDEX fuel_coupondistribution_beneficiary_id_idx ON fuel_coupondistribution(beneficiary_id);
            CREATE INDEX fuel_coupondistribution_program_id_idx ON fuel_coupondistribution(program_id);
            CREATE INDEX fuel_coupondistribution_distribution_date_idx ON fuel_coupondistribution(distribution_date);
            """,
            reverse_sql="-- No reverse operation"
        ),
    ]
