# Generated by Django 5.2 on 2025-07-07 11:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0016_auto_20250707_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('page_number', models.IntegerField(help_text='Page number within the book (1-100)')),
                ('first_coupon_number', models.CharField(help_text='First coupon number on this page', max_length=50)),
                ('last_coupon_number', models.CharField(help_text='Last coupon number on this page', max_length=50)),
                ('coupons_per_page', models.IntegerField(default=1, help_text='Number of coupons on this page (usually 1)')),
                ('is_used', models.BooleanField(default=False, help_text='Whether this page has been used')),
                ('used_date', models.DateTimeField(blank=True, help_text='When this page was used', null=True)),
            ],
            options={
                'verbose_name': 'Book Page',
                'verbose_name_plural': 'Book Pages',
                'ordering': ['book', 'page_number'],
            },
        ),
        migrations.AlterModelOptions(
            name='coupondistribution',
            options={'ordering': ['-distribution_date'], 'verbose_name': 'Coupon Distribution', 'verbose_name_plural': 'Coupon Distributions'},
        ),
        migrations.AlterModelOptions(
            name='vehiclecategory',
            options={'ordering': ['name'], 'verbose_name': 'Vehicle Category', 'verbose_name_plural': 'Vehicle Categories'},
        ),
        migrations.RemoveIndex(
            model_name='systemalert',
            name='fuel_system_auto_re_1fed0f_idx',
        ),
        migrations.RemoveField(
            model_name='beneficiarycategory',
            name='base_entitlement_litres',
        ),
        migrations.RemoveField(
            model_name='beneficiarycategory',
            name='category_type',
        ),
        migrations.RemoveField(
            model_name='constituency',
            name='code',
        ),
        migrations.RemoveField(
            model_name='couponallocation',
            name='coupons',
        ),
        migrations.RemoveField(
            model_name='parliamentsession',
            name='fuel_entitlement_litres',
        ),
        migrations.RemoveField(
            model_name='parliamentsession',
            name='is_mandatory',
        ),
        migrations.RemoveField(
            model_name='parliamentsession',
            name='session_manager',
        ),
        migrations.RemoveField(
            model_name='parliamentsession',
            name='venue',
        ),
        migrations.RemoveField(
            model_name='systemalert',
            name='auto_resolve_at',
        ),
        migrations.RemoveField(
            model_name='vehiclecategory',
            name='max_engine_cc',
        ),
        migrations.RemoveField(
            model_name='vehiclecategory',
            name='min_engine_cc',
        ),
        migrations.AddField(
            model_name='beneficiarycategory',
            name='monthly_entitlement_litres',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Default monthly fuel entitlement in litres', max_digits=8),
        ),
        migrations.AddField(
            model_name='constituency',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='constituency',
            name='population',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='couponallocation',
            name='book',
            field=models.ForeignKey(blank=True, help_text='Book this allocation relates to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='fuel.book'),
        ),
        migrations.AddField(
            model_name='couponallocation',
            name='first_coupon_number',
            field=models.CharField(blank=True, help_text='First coupon in the allocated range', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='couponallocation',
            name='last_coupon_number',
            field=models.CharField(blank=True, help_text='Last coupon in the allocated range', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='couponallocation',
            name='quantity',
            field=models.IntegerField(blank=True, help_text='Number of coupons allocated', null=True),
        ),
        migrations.AddField(
            model_name='parliamentsession',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='parliamentsession',
            name='organizer',
            field=models.ForeignKey(help_text='Officer responsible for managing this parliament session', limit_choices_to={'role__in': ['MAIN_CENTER', 'SUB_CENTER']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehiclecategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vehiclecategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='beneficiarycategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='box',
            name='coupons_per_book',
            field=models.IntegerField(default=100, help_text='Number of coupons per book (usually 100 pages/coupons)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='constituency',
            name='distance_from_parliament_km',
            field=models.IntegerField(default=0, help_text='Distance from Parliament in kilometers'),
        ),
        migrations.AlterField(
            model_name='coupondistribution',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='fuel.coupon'),
        ),
        migrations.AlterField(
            model_name='coupondistribution',
            name='distributed_by',
            field=models.ForeignKey(limit_choices_to={'role__in': ['MAIN_CENTER', 'SUB_CENTER']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_distributions_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coupondistribution',
            name='distribution_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='parliamentsession',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='parliamentsession',
            name='session_type',
            field=models.CharField(choices=[('REGULAR', 'Regular Session'), ('SPECIAL', 'Special Session'), ('COMMITTEE', 'Committee Session'), ('BUDGET', 'Budget Session'), ('EMERGENCY', 'Emergency Session')], default='REGULAR', max_length=20),
        ),
        migrations.AlterField(
            model_name='parliamentsession',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='systemalert',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, help_text='When the alert was acknowledged', null=True),
        ),
        migrations.AlterField(
            model_name='systemalert',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, help_text='User who acknowledged the alert', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='systemalert',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created the alert', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehiclecategory',
            name='fuel_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Multiplier for fuel entitlement based on vehicle category', max_digits=4),
        ),
        migrations.AlterField(
            model_name='vehiclecategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='bookpage',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='fuel.book'),
        ),
        migrations.AddField(
            model_name='bookpage',
            name='used_by',
            field=models.ForeignKey(blank=True, help_text='User who used this page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_pages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coupon',
            name='page',
            field=models.ForeignKey(blank=True, help_text='The page this coupon belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='fuel.bookpage'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['page'], name='fuel_coupon_page_id_1fed85_idx'),
        ),
        migrations.AddIndex(
            model_name='bookpage',
            index=models.Index(fields=['book', 'page_number'], name='fuel_bookpa_book_id_a743f3_idx'),
        ),
        migrations.AddIndex(
            model_name='bookpage',
            index=models.Index(fields=['is_used'], name='fuel_bookpa_is_used_b9782c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bookpage',
            unique_together={('book', 'page_number')},
        ),
    ]
