# Generated by Django 5.2 on 2025-07-24 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0008_bc_integration_fields'),
        ('fuel', '0017_bookpage_alter_coupondistribution_options_and_more'),
    ]

    operations = [
    ]
