# Generated by Django - Fix for empty migration file
from django.db import migrations


class Migration(migrations.Migration):
    
    dependencies = [
        ('fuel', '0022_bookdispatch_serial_fields'),
    ]

    operations = [
        # No operations - this is a fix for an empty migration file
    ]
