# Generated by Django 5.2 on 2025-08-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0024_harmonize_box_fields_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdispatch',
            name='courier_service',
            field=models.CharField(blank=True, help_text='Courier service name', max_length=100),
        ),
        migrations.AddField(
            model_name='bookdispatch',
            name='delivery_note',
            field=models.CharField(blank=True, help_text='Delivery note reference', max_length=200),
        ),
        migrations.AddField(
            model_name='bookdispatch',
            name='driver_name',
            field=models.CharField(blank=True, help_text='Name of the driver', max_length=100),
        ),
        migrations.AddField(
            model_name='bookdispatch',
            name='driver_phone',
            field=models.CharField(blank=True, help_text="Driver's phone number", max_length=20),
        ),
        migrations.AddField(
            model_name='bookdispatch',
            name='generation_mode',
            field=models.CharField(blank=True, help_text='Mode used for intelligent generation', max_length=50),
        ),
        migrations.AddField(
            model_name='bookdispatch',
            name='receiver_signature',
            field=models.TextField(blank=True, help_text='Digital signature data of receiver'),
        ),
        migrations.AddField(
            model_name='bookdispatch',
            name='special_instructions',
            field=models.TextField(blank=True, help_text='Special delivery instructions'),
        ),
        migrations.AddField(
            model_name='bookdispatch',
            name='tracking_number',
            field=models.CharField(blank=True, help_text='Tracking number for shipment', max_length=50),
        ),
        migrations.AddField(
            model_name='bookdispatch',
            name='transport_method',
            field=models.CharField(choices=[('DIRECT_DELIVERY', 'Direct Delivery'), ('PICKUP', 'Pickup'), ('COURIER', 'Courier Service'), ('GOVERNMENT_VEHICLE', 'Government Vehicle')], default='DIRECT_DELIVERY', help_text='Method of transport for delivery', max_length=50),
        ),
        migrations.AddField(
            model_name='bookdispatch',
            name='vehicle_number',
            field=models.CharField(blank=True, help_text='Vehicle registration number', max_length=20),
        ),
        migrations.AddField(
            model_name='bookdispatch',
            name='verification_checks',
            field=models.JSONField(blank=True, default=list, help_text='List of completed verification checks'),
        ),
        migrations.AddField(
            model_name='bookdispatch',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Notes from verification process'),
        ),
        migrations.AddField(
            model_name='bookdispatch',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When verification was completed', null=True),
        ),
        migrations.AddField(
            model_name='bookdispatch',
            name='verified_by',
            field=models.CharField(blank=True, help_text='Name of person who verified', max_length=100),
        ),
        migrations.AlterField(
            model_name='bookdispatch',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIGURED', 'Configured'), ('VERIFIED', 'Verified'), ('DISPATCHED', 'Dispatched'), ('RECEIVED', 'Received'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
