# Generated by Django 5.2 on 2025-08-11 19:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0026_create_coupon_handover_enhanced'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('allocation_id', models.CharField(help_text='Unique allocation identifier', max_length=50, unique=True)),
                ('allocation_type', models.CharField(choices=[('REGULAR', 'Regular Allocation'), ('SESSION_BASED', 'Parliament Session'), ('EMERGENCY', 'Emergency Allocation'), ('ADJUSTMENT', 'Adjustment/Correction'), ('BONUS', 'Bonus Allocation')], default='REGULAR', help_text='Type of allocation', max_length=20)),
                ('status', models.CharField(choices=[('PREVIEW', 'Preview (Not Committed)'), ('COMMITTED', 'Committed'), ('PARTIALLY_FULFILLED', 'Partially Fulfilled'), ('FULFILLED', 'Fully Fulfilled'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PREVIEW', help_text='Current status of allocation', max_length=20)),
                ('allocation_period_start', models.DateField(help_text='Start date of allocation period')),
                ('allocation_period_end', models.DateField(help_text='End date of allocation period')),
                ('period_type', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], default='MONTHLY', help_text='Type of allocation period', max_length=20)),
                ('base_allocation_litres', models.DecimalField(decimal_places=2, help_text='Base allocation before supplements', max_digits=10)),
                ('session_supplement_litres', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Additional litres for session attendance', max_digits=10)),
                ('total_allocation_litres', models.DecimalField(decimal_places=2, help_text='Total allocated litres', max_digits=10)),
                ('allocated_value_usd', models.DecimalField(decimal_places=4, help_text='USD value of allocation', max_digits=12)),
                ('calculation_details', models.JSONField(default=dict, help_text='Detailed calculation breakdown')),
                ('engine_capacity_cc', models.IntegerField(help_text='Engine capacity used in calculation')),
                ('distance_from_parliament_km', models.IntegerField(help_text='Distance from parliament used in calculation')),
                ('engine_constant_applied', models.DecimalField(decimal_places=4, help_text='Engine constant rate used', max_digits=6)),
                ('distance_factor_applied', models.DecimalField(decimal_places=4, help_text='Distance factor applied', max_digits=6)),
                ('fuel_price_used', models.DecimalField(decimal_places=4, help_text='Fuel price per litre used', max_digits=8)),
                ('coupons_allocated', models.IntegerField(default=0, help_text='Number of coupons allocated to fulfill this allocation')),
                ('litres_fulfilled', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Litres actually provided via coupons', max_digits=10)),
                ('remaining_litres', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Remaining litres to be fulfilled', max_digits=10)),
                ('committed_at', models.DateTimeField(blank=True, help_text='When this allocation was committed', null=True)),
                ('approved_at', models.DateTimeField(blank=True, help_text='When this allocation was approved', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this allocation')),
                ('preview_generated_at', models.DateTimeField(auto_now_add=True, help_text='When the allocation preview was generated')),
            ],
            options={
                'verbose_name': 'Dynamic Allocation',
                'verbose_name_plural': 'Dynamic Allocations',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='FuelAllocationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('rule_name', models.CharField(help_text='Unique name for this allocation rule', max_length=200, unique=True)),
                ('rule_type', models.CharField(choices=[('BASE_ALLOCATION', 'Base Allocation Rule'), ('ENGINE_MULTIPLIER', 'Engine Capacity Multiplier'), ('DISTANCE_FACTOR', 'Distance-Based Factor'), ('SESSION_SUPPLEMENT', 'Parliament Session Supplement'), ('CATEGORY_BONUS', 'Category-Based Bonus'), ('EMERGENCY_ALLOCATION', 'Emergency Allocation')], help_text='Type of allocation rule', max_length=30)),
                ('rule_code', models.CharField(help_text='Unique code for API/system reference', max_length=50, unique=True)),
                ('description', models.TextField(help_text='Detailed description of the rule and its purpose')),
                ('applies_to_engine_band', models.CharField(blank=True, choices=[('UNDER_2800', 'Under 2800cc'), ('2800_TO_3199', '2800cc - 3199cc'), ('3200_AND_ABOVE', '3200cc and above')], help_text='Engine capacity band this rule applies to', max_length=20, null=True)),
                ('applies_to_distance_min', models.IntegerField(blank=True, help_text='Minimum distance from parliament (km) for this rule', null=True)),
                ('applies_to_distance_max', models.IntegerField(blank=True, help_text='Maximum distance from parliament (km) for this rule', null=True)),
                ('period_type', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], default='MONTHLY', help_text='Period for which this allocation applies', max_length=20)),
                ('engine_constant_under_2800', models.DecimalField(decimal_places=4, default=Decimal('0.39'), help_text='Rate constant for engines under 2800cc', max_digits=6)),
                ('engine_constant_2800_3199', models.DecimalField(decimal_places=4, default=Decimal('0.43'), help_text='Rate constant for engines 2800-3199cc', max_digits=6)),
                ('engine_constant_3200_plus', models.DecimalField(decimal_places=4, default=Decimal('0.56'), help_text='Rate constant for engines 3200cc and above', max_digits=6)),
                ('distance_factor_base', models.DecimalField(decimal_places=4, default=Decimal('1.0'), help_text='Base distance factor (no distance adjustment)', max_digits=6)),
                ('distance_factor_per_km', models.DecimalField(decimal_places=6, default=Decimal('0.001'), help_text='Additional factor per kilometer from parliament', max_digits=8)),
                ('max_distance_factor', models.DecimalField(decimal_places=4, default=Decimal('2.0'), help_text='Maximum distance factor cap', max_digits=6)),
                ('minimum_allocation_litres', models.DecimalField(decimal_places=2, default=Decimal('20'), help_text='Minimum allocation regardless of calculation', max_digits=8)),
                ('maximum_allocation_litres', models.DecimalField(decimal_places=2, default=Decimal('500'), help_text='Maximum allocation cap', max_digits=8)),
                ('session_top_up_litres', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Additional litres for parliament session attendance', max_digits=8)),
                ('session_top_up_percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Percentage-based session top-up', max_digits=6)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this rule is currently active')),
                ('effective_from', models.DateField(help_text='Date from which this rule is effective')),
                ('effective_until', models.DateField(blank=True, help_text='Date until which this rule is effective', null=True)),
                ('priority', models.IntegerField(default=100, help_text='Rule priority (lower numbers = higher priority)')),
                ('custom_formula', models.TextField(blank=True, help_text='Custom allocation formula (Python expression)')),
            ],
            options={
                'verbose_name': 'Fuel Allocation Rule',
                'verbose_name_plural': 'Fuel Allocation Rules',
                'ordering': ['priority', 'rule_name'],
            },
        ),
        migrations.CreateModel(
            name='FuelPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('fuel_type', models.CharField(choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel'), ('BOTH', 'Both (same price)')], help_text='Type of fuel this price applies to', max_length=10)),
                ('price_per_litre_usd', models.DecimalField(decimal_places=4, help_text='Price per litre in USD', max_digits=8)),
                ('price_per_litre_zwg', models.DecimalField(blank=True, decimal_places=2, help_text='Price per litre in ZWG (optional, for reference)', max_digits=12, null=True)),
                ('exchange_rate_usd_zwg', models.DecimalField(blank=True, decimal_places=4, help_text='USD to ZWG exchange rate used', max_digits=12, null=True)),
                ('effective_date', models.DateField(help_text='Date from which this price is effective')),
                ('expiry_date', models.DateField(blank=True, help_text='Date until which this price is valid', null=True)),
                ('price_source', models.CharField(choices=[('MANUAL', 'Manual Entry'), ('GOVERNMENT_GAZETTE', 'Government Gazette'), ('ENERGY_MINISTRY', 'Ministry of Energy'), ('MARKET_RATE', 'Market Rate'), ('API_FEED', 'API Data Feed')], default='MANUAL', help_text='Source of this price information', max_length=30)),
                ('source_reference', models.CharField(blank=True, help_text='Reference number or document from source', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this price is currently active')),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default price when no specific price found')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this price')),
                ('approved_at', models.DateTimeField(blank=True, help_text='When this price was approved', null=True)),
            ],
            options={
                'verbose_name': 'Fuel Price',
                'verbose_name_plural': 'Fuel Prices',
                'ordering': ['-effective_date', '-created'],
            },
        ),
        migrations.CreateModel(
            name='HarmonizedBeneficiaryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('parliamentary_id', models.CharField(help_text="Official parliamentary ID (maps to frontend 'parliamentaryId')", max_length=50, unique=True)),
                ('employee_id', models.CharField(blank=True, help_text='Legacy employee ID for backward compatibility', max_length=50, null=True, unique=True)),
                ('position', models.CharField(help_text="Official position title (maps to frontend 'title')", max_length=100)),
                ('department', models.CharField(blank=True, help_text='Department/Ministry', max_length=100)),
                ('party_affiliation', models.CharField(blank=True, help_text="Political party affiliation (maps to frontend 'party')", max_length=100)),
                ('date_of_birth', models.DateField(blank=True, help_text="Date of birth (maps to frontend 'dateOfBirth')", null=True)),
                ('national_id', models.CharField(help_text="National ID number (maps to frontend 'nationalId')", max_length=50, unique=True)),
                ('full_address', models.TextField(help_text="Complete residential address (maps to frontend 'address')")),
                ('office_location', models.CharField(blank=True, help_text='Office location/room number', max_length=200)),
                ('office_phone', models.CharField(blank=True, help_text='Office phone number', max_length=20)),
                ('mobile_phone', models.CharField(help_text="Mobile phone number (maps to frontend 'phoneNumber')", max_length=20)),
                ('official_email', models.EmailField(help_text="Official email address (maps to frontend 'email')", max_length=254)),
                ('personal_email', models.EmailField(blank=True, help_text='Personal email address', max_length=254)),
                ('vehicle_make', models.CharField(help_text='Vehicle manufacturer (e.g., Toyota, Mercedes)', max_length=50)),
                ('vehicle_model', models.CharField(help_text='Vehicle model (e.g., Prado, C-Class)', max_length=50)),
                ('vehicle_year', models.IntegerField(help_text='Year of manufacture', validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2030)])),
                ('engine_size', models.CharField(help_text='Engine size (e.g., 2.0L, 3.0L V6)', max_length=20)),
                ('vehicle_registration', models.CharField(help_text='Vehicle registration number', max_length=20, unique=True)),
                ('fuel_type', models.CharField(choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel')], default='DIESEL', help_text='Type of fuel the vehicle uses', max_length=10)),
                ('base_allocation', models.DecimalField(decimal_places=2, default=Decimal('200'), help_text='Base monthly allocation before multipliers', max_digits=8)),
                ('category_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.0'), help_text='Role-based multiplier (MP: 1.5, Senator: 1.4, etc.)', max_digits=4)),
                ('engine_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.0'), help_text='Engine size-based multiplier', max_digits=4)),
                ('monthly_entitlement_litres', models.DecimalField(decimal_places=2, help_text='Final monthly fuel entitlement in litres', max_digits=8)),
                ('max_per_transaction', models.DecimalField(decimal_places=2, default=Decimal('50'), help_text='Maximum litres per single transaction', max_digits=8)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], default='ACTIVE', help_text="Current beneficiary status (maps to frontend 'status')", max_length=20)),
                ('is_active_beneficiary', models.BooleanField(default=True, help_text='Boolean flag for active status')),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Current fuel balance in litres', max_digits=8)),
                ('used_this_month', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Fuel used in current month', max_digits=8)),
                ('last_month_usage', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Fuel used in previous month', max_digits=8)),
                ('year_to_date_usage', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total fuel used this year', max_digits=8)),
                ('total_usage_all_time', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total fuel used since registration', max_digits=8)),
                ('last_allocation_date', models.DateTimeField(blank=True, help_text='Date of last fuel allocation', null=True)),
                ('join_date', models.DateField(auto_now_add=True, help_text="Date when beneficiary joined (maps to frontend 'createdAt')")),
                ('last_login', models.DateTimeField(blank=True, help_text='Last login timestamp', null=True)),
            ],
            options={
                'verbose_name': 'Harmonized Beneficiary Profile',
                'verbose_name_plural': 'Harmonized Beneficiary Profiles',
                'db_table': 'fuel_harmonized_beneficiary_profile',
                'ordering': ['user__username'],
            },
        ),
        migrations.RemoveField(
            model_name='couponhandover',
            name='updated',
        ),
        migrations.AddField(
            model_name='beneficiaryprofile',
            name='distance_from_parliament_km',
            field=models.IntegerField(blank=True, help_text='Distance from Parliament in kilometers (auto-populated from constituency)', null=True),
        ),
        migrations.AddField(
            model_name='beneficiaryprofile',
            name='engine_capacity_cc',
            field=models.IntegerField(blank=True, help_text='Engine capacity in cubic centimeters for allocation calculations', null=True),
        ),
        migrations.AddField(
            model_name='couponhandover',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='parliamentsession',
            name='attendance_tracked',
            field=models.BooleanField(default=False, help_text='Whether attendance is being tracked for this session'),
        ),
        migrations.AddField(
            model_name='parliamentsession',
            name='expected_attendance',
            field=models.IntegerField(default=0, help_text='Expected number of attendees'),
        ),
        migrations.AddField(
            model_name='parliamentsession',
            name='fuel_top_up_litres',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Additional fuel litres for session attendees', max_digits=8),
        ),
        migrations.AddField(
            model_name='parliamentsession',
            name='fuel_top_up_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Percentage-based fuel top-up for session attendees', max_digits=6),
        ),
        migrations.AlterField(
            model_name='couponhandover',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddIndex(
            model_name='couponhandover',
            index=models.Index(fields=['beneficiary'], name='fuel_coupon_benefic_1619cd_idx'),
        ),
        migrations.AddIndex(
            model_name='couponhandover',
            index=models.Index(fields=['status'], name='fuel_coupon_status_128328_idx'),
        ),
        migrations.AddIndex(
            model_name='couponhandover',
            index=models.Index(fields=['handed_over_date'], name='fuel_coupon_handed__d89119_idx'),
        ),
        migrations.AddIndex(
            model_name='couponhandover',
            index=models.Index(fields=['sub_center'], name='fuel_coupon_sub_cen_ceac87_idx'),
        ),
        migrations.AddIndex(
            model_name='couponhandover',
            index=models.Index(fields=['handover_mode'], name='fuel_coupon_handove_65c7f6_idx'),
        ),
        migrations.AddField(
            model_name='dynamicallocation',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='User who approved this allocation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_dynamic_allocations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dynamicallocation',
            name='beneficiary',
            field=models.ForeignKey(help_text='Beneficiary receiving this allocation', on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_allocations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dynamicallocation',
            name='committed_by',
            field=models.ForeignKey(blank=True, help_text='User who committed this allocation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committed_dynamic_allocations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dynamicallocation',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this allocation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dynamic_allocations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dynamicallocation',
            name='parliament_session',
            field=models.ForeignKey(blank=True, help_text='Related parliament session (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dynamic_allocations', to='fuel.parliamentsession'),
        ),
        migrations.AddField(
            model_name='fuelallocationrule',
            name='applies_to_category',
            field=models.ForeignKey(blank=True, help_text='Beneficiary category this rule applies to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocation_rules', to='fuel.beneficiarycategory'),
        ),
        migrations.AddField(
            model_name='fuelallocationrule',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this rule', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_allocation_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fuelallocationrule',
            name='last_modified_by',
            field=models.ForeignKey(help_text='User who last modified this rule', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_allocation_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dynamicallocation',
            name='rule_applied',
            field=models.ForeignKey(help_text='Allocation rule used for calculation', on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='fuel.fuelallocationrule'),
        ),
        migrations.AddField(
            model_name='fuelprice',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='User who approved this price', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_fuel_prices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fuelprice',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this price record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fuel_prices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dynamicallocation',
            name='fuel_price',
            field=models.ForeignKey(help_text='Fuel price used for calculation', on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='fuel.fuelprice'),
        ),
        migrations.AddField(
            model_name='harmonizedbeneficiaryprofile',
            name='category',
            field=models.ForeignKey(help_text='Beneficiary category (MP, SENATOR, STAFF, etc.)', on_delete=django.db.models.deletion.PROTECT, related_name='harmonized_beneficiaries', to='fuel.beneficiarycategory'),
        ),
        migrations.AddField(
            model_name='harmonizedbeneficiaryprofile',
            name='constituency',
            field=models.ForeignKey(blank=True, help_text='Associated constituency', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harmonized_constituency_beneficiaries', to='fuel.constituency'),
        ),
        migrations.AddField(
            model_name='harmonizedbeneficiaryprofile',
            name='user',
            field=models.OneToOneField(help_text='Associated user account', on_delete=django.db.models.deletion.CASCADE, related_name='harmonized_beneficiary_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='harmonizedbeneficiaryprofile',
            name='vehicle_category',
            field=models.ForeignKey(blank=True, help_text='Vehicle category for allocation calculations', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harmonized_vehicle_beneficiaries', to='fuel.vehiclecategory'),
        ),
        migrations.AddIndex(
            model_name='fuelallocationrule',
            index=models.Index(fields=['rule_type', 'is_active'], name='fuel_fuelal_rule_ty_76552a_idx'),
        ),
        migrations.AddIndex(
            model_name='fuelallocationrule',
            index=models.Index(fields=['applies_to_engine_band'], name='fuel_fuelal_applies_e7cdeb_idx'),
        ),
        migrations.AddIndex(
            model_name='fuelallocationrule',
            index=models.Index(fields=['applies_to_category'], name='fuel_fuelal_applies_357190_idx'),
        ),
        migrations.AddIndex(
            model_name='fuelallocationrule',
            index=models.Index(fields=['effective_from', 'effective_until'], name='fuel_fuelal_effecti_864c18_idx'),
        ),
        migrations.AddIndex(
            model_name='fuelallocationrule',
            index=models.Index(fields=['priority'], name='fuel_fuelal_priorit_be30c0_idx'),
        ),
        migrations.AddIndex(
            model_name='fuelprice',
            index=models.Index(fields=['fuel_type', 'effective_date'], name='fuel_fuelpr_fuel_ty_824273_idx'),
        ),
        migrations.AddIndex(
            model_name='fuelprice',
            index=models.Index(fields=['is_active', 'is_default'], name='fuel_fuelpr_is_acti_71938f_idx'),
        ),
        migrations.AddIndex(
            model_name='fuelprice',
            index=models.Index(fields=['effective_date', 'expiry_date'], name='fuel_fuelpr_effecti_7cf200_idx'),
        ),
        migrations.AddIndex(
            model_name='dynamicallocation',
            index=models.Index(fields=['beneficiary', 'status'], name='fuel_dynami_benefic_7f221e_idx'),
        ),
        migrations.AddIndex(
            model_name='dynamicallocation',
            index=models.Index(fields=['allocation_period_start', 'allocation_period_end'], name='fuel_dynami_allocat_a14571_idx'),
        ),
        migrations.AddIndex(
            model_name='dynamicallocation',
            index=models.Index(fields=['status', 'allocation_type'], name='fuel_dynami_status_c5efcf_idx'),
        ),
        migrations.AddIndex(
            model_name='dynamicallocation',
            index=models.Index(fields=['parliament_session'], name='fuel_dynami_parliam_e9c2b1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dynamicallocation',
            unique_together={('beneficiary', 'allocation_period_start', 'allocation_period_end', 'allocation_type')},
        ),
    ]
