# Generated by Django 5.2 on 2025-08-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0027_dynamicallocation_fuelallocationrule_fuelprice_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemalert',
            options={'ordering': ['-priority', '-created'], 'verbose_name': 'System Alert', 'verbose_name_plural': 'System Alerts'},
        ),
        migrations.RemoveField(
            model_name='systemalert',
            name='content_type',
        ),
        migrations.AddField(
            model_name='systemalert',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When this alert expires (null means never expires)', null=True),
        ),
        migrations.AddField(
            model_name='systemalert',
            name='is_dismissible',
            field=models.BooleanField(default=True, help_text='Whether users can dismiss this alert'),
        ),
        migrations.AddField(
            model_name='systemalert',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=2, help_text='Alert priority level'),
        ),
        migrations.AddField(
            model_name='systemalert',
            name='target_roles',
            field=models.JSONField(blank=True, help_text='Specific roles this alert targets (null means all roles)', null=True),
        ),
        migrations.AlterField(
            model_name='systemalert',
            name='object_id',
            field=models.CharField(blank=True, help_text='Related object ID', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='systemalert',
            index=models.Index(fields=['priority'], name='fuel_system_priorit_046edc_idx'),
        ),
        migrations.AddIndex(
            model_name='systemalert',
            index=models.Index(fields=['expires_at'], name='fuel_system_expires_a9d3d1_idx'),
        ),
    ]
