# Generated by Django 5.2 on 2025-08-16 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0029_beneficiaryprofile_status_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaryprofile',
            name='address',
            field=models.TextField(blank=True, help_text='Physical address'),
        ),
        migrations.AddField(
            model_name='beneficiaryprofile',
            name='chassis_number',
            field=models.CharField(blank=True, help_text='Vehicle chassis number', max_length=50),
        ),
        migrations.AddField(
            model_name='beneficiaryprofile',
            name='email',
            field=models.EmailField(blank=True, help_text='Contact email address', max_length=254),
        ),
        migrations.AddField(
            model_name='beneficiaryprofile',
            name='engine_number',
            field=models.CharField(blank=True, help_text='Vehicle engine number', max_length=50),
        ),
        migrations.AddField(
            model_name='beneficiaryprofile',
            name='parliamentary_id',
            field=models.CharField(blank=True, help_text='Parliamentary identification number', max_length=50),
        ),
        migrations.AddField(
            model_name='beneficiaryprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=20),
        ),
        migrations.AddField(
            model_name='beneficiaryprofile',
            name='term_end_date',
            field=models.DateField(blank=True, help_text='End date of parliamentary term', null=True),
        ),
        migrations.AddField(
            model_name='beneficiaryprofile',
            name='term_start_date',
            field=models.DateField(blank=True, help_text='Start date of parliamentary term', null=True),
        ),
        migrations.AddField(
            model_name='beneficiaryprofile',
            name='vehicle_color',
            field=models.CharField(blank=True, help_text='Vehicle color', max_length=50),
        ),
    ]
