# Generated by Django 5.2 on 2025-08-16 05:45

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0030_beneficiaryprofile_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiaryVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('registration', models.CharField(max_length=20)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('fuel_type', models.CharField(choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel')], default='PETROL', max_length=20)),
                ('engine_size', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deactivated_date', models.DateTimeField(blank=True, null=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_vehicles', to='fuel.harmonizedbeneficiaryprofile')),
            ],
            options={
                'verbose_name': 'Beneficiary Vehicle',
                'verbose_name_plural': 'Beneficiary Vehicles',
                'ordering': ['-created'],
            },
        ),
    ]
