# Generated by Django 5.2 on 2025-08-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0035_add_is_mandatory_to_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='parliamentsession',
            name='venue',
            field=models.CharField(default='Parliament Building', help_text='Location where the session will be held', max_length=200),
        ),
    ]
