# Generated by Django 5.2 on 2025-08-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0036_add_venue_to_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='parliamentsession',
            name='assigned_attendees',
            field=models.ManyToManyField(blank=True, help_text='Beneficiaries assigned to attend this session', related_name='assigned_sessions', to='fuel.beneficiaryprofile'),
        ),
    ]
