# Generated by Django 5.0.7 on 2025-08-19 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0039_add_frontend_alignment_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='received_by',
            field=models.ForeignKey(limit_choices_to={'role__in': ['MAIN_CENTER', 'SUB_CENTER', 'SUPERUSER']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_boxes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coupondistribution',
            name='distributed_by',
            field=models.ForeignKey(limit_choices_to={'role__in': ['MAIN_CENTER', 'SUB_CENTER', 'SUPERUSER']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_distributions_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parliamentsession',
            name='organizer',
            field=models.ForeignKey(help_text='Officer responsible for managing this parliament session', limit_choices_to={'role__in': ['MAIN_CENTER', 'SUB_CENTER', 'SUPERUSER']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subcenter',
            name='managed_by',
            field=models.ForeignKey(limit_choices_to={'role__in': ['MAIN_CENTER', 'SUB_CENTER', 'SUPERUSER']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_centers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subcenterofficer',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role__in': ['MAIN_CENTER', 'SUB_CENTER', 'SUPERUSER']}, on_delete=django.db.models.deletion.CASCADE, related_name='officer_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
