# Generated by Django 5.2 on 2025-08-20 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0040_alter_box_received_by_and_more'),
        ('fuel', '10004_backfill_bookdispatch_program_session'),
    ]

    operations = [
    ]
