from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0002_add_missing_fields'),
        ('fuel', '10001_add_fuel_requirement_configuration'),
    ]

    operations = []
# Generated by Django 5.2 on 2025-08-11 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0002_add_missing_fields'),
        ('fuel', '10001_add_fuel_requirement_configuration'),
    ]

    operations = [
    ]
