# Generated by Django 5.2 on 2025-08-10 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0002_add_missing_fields'),
        ('fuel', '0024_add_user_profile_fields'),
        ('fuel', '9999_enhance_beneficiary_models'),
    ]

    operations = [
    ]
