# Generated by Django 5.2 on 2025-08-20 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '10007_remove_bookdispatch_books_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='books_dispatched',
            field=models.IntegerField(default=0, help_text='Number of books that have been dispatched from this box', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='box',
            name='coupons_used',
            field=models.IntegerField(default=0, help_text='Number of coupons that have been used from this box', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='box',
            name='litres_used',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total litres worth of coupons that have been used', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='box',
            name='location',
            field=models.CharField(default='Main Warehouse', help_text='Current physical location of this box', max_length=200),
        ),
    ]
