# Generated by Django 5.2 on 2025-08-31 15:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '10011_add_contact_person_to_subcenter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiaryprofile',
            name='party_affiliation',
        ),
        migrations.RemoveField(
            model_name='harmonizedbeneficiaryprofile',
            name='party_affiliation',
        ),
        migrations.CreateModel(
            name='PoliticalParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full party name (e.g., Zimbabwe African National Union - Patriotic Front)', max_length=200, unique=True)),
                ('short_name', models.CharField(help_text='Short name or acronym (e.g., ZANU-PF)', max_length=50, unique=True)),
                ('abbreviation', models.CharField(blank=True, help_text='Official abbreviation if different from short name', max_length=20, null=True)),
                ('party_type', models.CharField(choices=[('POLITICAL', 'Political Party'), ('COALITION', 'Coalition'), ('ALLIANCE', 'Alliance'), ('INDEPENDENT', 'Independent'), ('OTHER', 'Other')], default='POLITICAL', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DISBANDED', 'Disbanded'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
                ('headquarters_address', models.TextField(blank=True, help_text='Main headquarters address', null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('contact_email', models.EmailField(blank=True, help_text='Official party email', max_length=254, null=True)),
                ('website', models.URLField(blank=True, help_text='Official party website', null=True)),
                ('leader_name', models.CharField(blank=True, help_text='Current party leader', max_length=200, null=True)),
                ('leader_title', models.CharField(blank=True, help_text="Leader's official title (e.g., President, Chairperson)", max_length=100, null=True)),
                ('founded_date', models.DateField(blank=True, help_text='Date the party was founded', null=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of the party', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_government_party', models.BooleanField(default=False, help_text='Is this currently the ruling party?')),
                ('is_parliamentary_party', models.BooleanField(default=True, help_text='Does this party have parliamentary representation?')),
                ('display_order', models.PositiveIntegerField(default=100, help_text='Display order in dropdowns (lower numbers first)')),
                ('primary_color', models.CharField(blank=True, help_text='Primary party color (hex code, e.g., #FF0000)', max_length=7, null=True)),
                ('secondary_color', models.CharField(blank=True, help_text='Secondary party color (hex code)', max_length=7, null=True)),
            ],
            options={
                'verbose_name': 'Political Party',
                'verbose_name_plural': 'Political Parties',
                'db_table': 'fuel_political_party',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['status', 'is_parliamentary_party'], name='fuel_politi_status_e843cf_idx'), models.Index(fields=['display_order'], name='fuel_politi_display_3133e3_idx'), models.Index(fields=['short_name'], name='fuel_politi_short_n_c7e10f_idx')],
            },
        ),
        migrations.AddField(
            model_name='beneficiaryprofile',
            name='political_party',
            field=models.ForeignKey(blank=True, help_text='Political party affiliation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiaries', to='fuel.politicalparty'),
        ),
        migrations.AddField(
            model_name='harmonizedbeneficiaryprofile',
            name='political_party',
            field=models.ForeignKey(blank=True, help_text='Political party affiliation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harmonized_beneficiaries', to='fuel.politicalparty'),
        ),
    ]
