# Generated by Django 5.2 on 2025-09-21 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '10016_add_handover_fields_to_bookdispatch'),
    ]

    operations = [
    ]
