# Generated by Django 5.2 on 2025-08-31 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '10012_remove_beneficiaryprofile_party_affiliation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaryprofile',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Beneficiary category - optional, can be set later', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='beneficiaries', to='fuel.beneficiarycategory'),
        ),
        migrations.AlterField(
            model_name='harmonizedbeneficiaryprofile',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Beneficiary category - optional, can be set later', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='harmonized_beneficiaries', to='fuel.beneficiarycategory'),
        ),
    ]
