# Generated by Django 5.2 on 2025-08-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '10010_attendance_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcenter',
            name='contact_person',
            field=models.CharField(blank=True, help_text='Name of the primary contact person at the sub-center', max_length=100, null=True),
        ),
    ]
