# Generated by Django 5.2 on 2025-09-20 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '10015_bookdispatch_books_bookdispatch_dispatch_type_and_more'),
    ]

    operations = [
    ]
