# Generated by Django 5.2 on 2025-09-20 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '10014_alter_fuelentitlement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdispatch',
            name='books',
            field=models.ManyToManyField(blank=True, help_text='Books included in this dispatch', related_name='dispatches', to='fuel.book'),
        ),
        migrations.AddField(
            model_name='bookdispatch',
            name='dispatch_type',
            field=models.CharField(choices=[('CENTER_TO_CENTER', 'Center to Center'), ('CENTER_TO_BENEFICIARY', 'Center to Beneficiary')], default='CENTER_TO_CENTER', max_length=25),
        ),
        migrations.AddField(
            model_name='bookdispatch',
            name='from_center',
            field=models.ForeignKey(blank=True, help_text='Center sending the dispatch', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_dispatches', to='fuel.subcenter'),
        ),
        migrations.AddField(
            model_name='bookdispatch',
            name='to_beneficiary',
            field=models.ForeignKey(blank=True, help_text='Beneficiary receiving the dispatch', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_dispatches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookdispatch',
            name='to_center',
            field=models.ForeignKey(blank=True, help_text='SubCenter receiving the dispatch', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_dispatches', to='fuel.subcenter'),
        ),
    ]
