# Generated by Django 5.0.7 on 2025-08-30 05:58

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '10009_add_verification_sign_off_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERUSER', 'Super User (Developer)'), ('ADMIN', 'System Administrator'), ('MAIN_CENTER', 'Main Center Officer'), ('SUB_CENTER', 'Sub Center Officer'), ('BENEFICIARY', 'Beneficiary'), ('AUDITOR', 'Auditor'), ('MAIN_CENTER_APPROVER', 'Main Center Approver'), ('SUB_CENTER_APPROVER', 'Sub Center Approver'), ('SERGEANT_OF_ARMS', 'Sergeant of Arms')], default='BENEFICIARY', max_length=20),
        ),
        migrations.CreateModel(
            name='AttendanceRegistryMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('expected_to_attend', models.BooleanField(default=True)),
                ('attendance_status', models.CharField(choices=[('PENDING', 'Pending'), ('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('EXCUSED', 'Excused'), ('LATE', 'Late')], default='PENDING', max_length=10)),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('marked_date', models.DateTimeField(blank=True, null=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registry_memberships', to='fuel.beneficiaryprofile')),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registry Member',
                'verbose_name_plural': 'Registry Members',
                'ordering': ['beneficiary__user__last_name', 'beneficiary__user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='HarmonizedBeneficiaryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('parliamentary_id', models.CharField(help_text='Official parliamentary identification number', max_length=50, unique=True)),
                ('employee_id', models.CharField(blank=True, help_text='Employee ID for staff members', max_length=50, null=True, unique=True)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('party_affiliation', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('national_id', models.CharField(max_length=50, unique=True)),
                ('full_address', models.TextField(blank=True)),
                ('office_location', models.CharField(blank=True, max_length=200)),
                ('office_phone', models.CharField(blank=True, max_length=20)),
                ('mobile_phone', models.CharField(blank=True, max_length=20)),
                ('official_email', models.EmailField(blank=True, max_length=254)),
                ('personal_email', models.EmailField(blank=True, max_length=254)),
                ('vehicle_make', models.CharField(blank=True, max_length=50)),
                ('vehicle_model', models.CharField(blank=True, max_length=50)),
                ('vehicle_year', models.IntegerField(blank=True, null=True)),
                ('engine_size', models.CharField(blank=True, max_length=20)),
                ('vehicle_registration', models.CharField(blank=True, max_length=20)),
                ('fuel_type', models.CharField(choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel')], default='DIESEL', max_length=10)),
                ('base_allocation', models.DecimalField(decimal_places=2, default=Decimal('200'), max_digits=8)),
                ('category_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.0'), max_digits=4)),
                ('engine_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.0'), max_digits=4)),
                ('monthly_entitlement_litres', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('max_per_transaction', models.DecimalField(decimal_places=2, default=Decimal('50'), max_digits=8)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended'), ('PENDING_APPROVAL', 'Pending Approval')], default='ACTIVE', max_length=20)),
                ('is_active_beneficiary', models.BooleanField(default=True)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('used_this_month', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('last_month_usage', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('year_to_date_usage', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('total_usage_all_time', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('last_allocation_date', models.DateTimeField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='harmonized_beneficiaries', to='fuel.beneficiarycategory')),
                ('constituency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harmonized_constituency_beneficiaries', to='fuel.constituency')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='harmonized_profile', to=settings.AUTH_USER_MODEL)),
                ('vehicle_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harmonized_vehicle_beneficiaries', to='fuel.vehiclecategory')),
            ],
            options={
                'verbose_name': 'Harmonized Beneficiary Profile',
                'verbose_name_plural': 'Harmonized Beneficiary Profiles',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='SessionAttendanceRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(help_text='Registry title/name', max_length=200)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('submitted_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('IN_PROGRESS', 'Marking in Progress'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=15)),
                ('reviewed_date', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('attendance_date', models.DateField(help_text='Date when attendance was/will be marked')),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_editable', models.BooleanField(default=True, help_text='Can Sergeant of Arms still edit?')),
                ('expected_attendees', models.ManyToManyField(related_name='expected_registries', through='fuel.AttendanceRegistryMember', to='fuel.beneficiaryprofile')),
                ('managing_subcenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_registries', to='fuel.subcenter')),
                ('marked_by', models.ForeignKey(limit_choices_to={'role': 'SERGEANT_OF_ARMS'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_registries', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_registries', to='fuel.program')),
                ('published_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_registries', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_registries', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_registries', to='fuel.parliamentsession')),
            ],
            options={
                'verbose_name': 'Attendance Registry',
                'verbose_name_plural': 'Attendance Registries',
                'ordering': ['-attendance_date', '-created'],
            },
        ),
        migrations.AddField(
            model_name='attendanceregistrymember',
            name='registry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='fuel.sessionattendanceregistry'),
        ),
        migrations.CreateModel(
            name='AttendanceCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('reason', models.TextField(help_text='Reason for correction request')),
                ('correction_details', models.JSONField(default=dict, help_text='Details of what needs to be corrected')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('reviewed_date', models.DateTimeField(blank=True, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(limit_choices_to={'role': 'SERGEANT_OF_ARMS'}, on_delete=django.db.models.deletion.CASCADE, related_name='requested_corrections', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_corrections', to=settings.AUTH_USER_MODEL)),
                ('registry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='fuel.sessionattendanceregistry')),
            ],
            options={
                'verbose_name': 'Attendance Correction',
                'verbose_name_plural': 'Attendance Corrections',
                'ordering': ['-created'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='attendanceregistrymember',
            unique_together={('registry', 'beneficiary')},
        ),
    ]
