# Generated by Django 5.2 on 2025-09-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '10017_sync_missing_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdispatch',
            name='main_center_dispatch_number',
            field=models.CharField(blank=True, help_text='Primary sequential number for Main Center tracking (auto-generated)', max_length=30, null=True, unique=True),
        ),
    ]
