# Generated by Django 4.1.13 on 2025-09-02 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '10013_make_category_nullable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fuelentitlement',
            options={'ordering': ['-created'], 'verbose_name': 'Fuel Entitlement', 'verbose_name_plural': 'Fuel Entitlements'},
        ),
        migrations.RemoveField(
            model_name='fuelentitlement',
            name='entitlement_amount',
        ),
        migrations.AddField(
            model_name='fuelentitlement',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='User who approved this entitlement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entitlements_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fuelentitlement',
            name='approved_date',
            field=models.DateTimeField(blank=True, help_text='Date when entitlement was approved', null=True),
        ),
        migrations.AddField(
            model_name='fuelentitlement',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this entitlement record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entitlements_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fuelentitlement',
            name='entitlement_type',
            field=models.CharField(choices=[('MONTHLY', 'Monthly Entitlement'), ('SESSION', 'Parliament Session'), ('COMMITTEE', 'Committee Meeting'), ('SPECIAL_EVENT', 'Special Event'), ('TRAVEL_ALLOWANCE', 'Travel Allowance'), ('EMERGENCY', 'Emergency Allocation'), ('CONSTITUENCY_WORK', 'Constituency Work')], default='MONTHLY', help_text='Type of entitlement', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fuelentitlement',
            name='justification',
            field=models.TextField(default='', help_text='Justification for this entitlement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fuelentitlement',
            name='litres_allocated',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount of fuel actually allocated/given', max_digits=8),
        ),
        migrations.AddField(
            model_name='fuelentitlement',
            name='litres_entitled',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount of fuel entitled in litres', max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fuelentitlement',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about this entitlement'),
        ),
        migrations.AddField(
            model_name='fuelentitlement',
            name='period_end',
            field=models.DateField(default=django.utils.timezone.now, help_text='End date of entitlement period'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fuelentitlement',
            name='period_start',
            field=models.DateField(default=django.utils.timezone.now, help_text='Start date of entitlement period'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fuelentitlement',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Related parliament session (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_entitlements', to='fuel.parliamentsession'),
        ),
        migrations.AddField(
            model_name='fuelentitlement',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('ALLOCATED', 'Allocated'), ('PARTIALLY_ALLOCATED', 'Partially Allocated'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='fuelentitlement',
            name='beneficiary',
            field=models.ForeignKey(default=1, help_text='Parliament member or staff entitled to fuel', limit_choices_to={'role': 'BENEFICIARY'}, on_delete=django.db.models.deletion.CASCADE, related_name='fuel_entitlements', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
