# Generated by Django 5.2 on 2025-09-28 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '10032_add_subcenter_to_beneficiary'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaryprofile',
            name='sub_center',
            field=models.ForeignKey(blank=True, help_text='Sub-center this beneficiary is assigned to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiaries', to='fuel.subcenter'),
        ),
    ]
