# Generated by Django 5.2 on 2025-09-25 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '10028_merge_production_conflicts'),
        ('fuel', '10029_dispatch_aggregates_stub'),
        ('fuel', '10030_merge_20250922_backend_leaf_resolution'),
    ]

    operations = [
    ]
