# Generated by Django 5.2 on 2025-07-21 16:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCentralConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Configuration name', max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('tenant_id', models.CharField(help_text='Azure AD Tenant ID', max_length=100)),
                ('environment_name', models.CharField(help_text='Business Central environment name', max_length=100)),
                ('environment_type', models.CharField(choices=[('SANDBOX', 'Sandbox'), ('PRODUCTION', 'Production')], default='SANDBOX', max_length=20)),
                ('base_url', models.URLField(help_text='Business Central API base URL')),
                ('client_id', models.CharField(help_text='Azure AD App Client ID', max_length=100)),
                ('company_id', models.CharField(blank=True, help_text='Business Central Company ID', max_length=100)),
                ('auto_sync_enabled', models.BooleanField(default=True)),
                ('batch_size', models.IntegerField(default=100, help_text='Records per batch sync')),
                ('sync_interval_minutes', models.IntegerField(default=15, help_text='Auto sync interval')),
                ('fuel_expense_account', models.CharField(default='6100', help_text='GL Account for fuel expenses', max_length=20)),
                ('coupon_inventory_account', models.CharField(default='1400', help_text='GL Account for coupon inventory', max_length=20)),
                ('cash_account', models.CharField(default='1000', help_text='GL Account for cash/bank', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_connection_test', models.DateTimeField(blank=True, null=True)),
                ('connection_status', models.CharField(default='UNKNOWN', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Business Central Configuration',
                'verbose_name_plural': 'Business Central Configurations',
            },
        ),
        migrations.CreateModel(
            name='SyncRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('source_model', models.CharField(help_text='Django model to sync from', max_length=100)),
                ('source_filters', models.JSONField(blank=True, default=dict, help_text='Filter criteria for source records')),
                ('bc_entity', models.CharField(help_text='Business Central entity type', max_length=100)),
                ('bc_endpoint', models.CharField(help_text='API endpoint path', max_length=200)),
                ('trigger_type', models.CharField(choices=[('REALTIME', 'Real-time (on save)'), ('SCHEDULED', 'Scheduled batch'), ('MANUAL', 'Manual only')], default='REALTIME', max_length=20)),
                ('field_mappings', models.JSONField(default=dict, help_text='Field mapping configuration')),
                ('transformation_rules', models.JSONField(blank=True, default=dict, help_text='Data transformation rules')),
                ('is_active', models.BooleanField(default=True)),
                ('last_executed', models.DateTimeField(blank=True, null=True)),
                ('execution_count', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sync Rule',
                'verbose_name_plural': 'Sync Rules',
            },
        ),
        migrations.CreateModel(
            name='DynamicsMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_model', models.CharField(help_text='Django model name', max_length=100)),
                ('local_id', models.CharField(help_text='Local system primary key', max_length=50)),
                ('bc_entity', models.CharField(choices=[('ITEM', 'Item'), ('CUSTOMER', 'Customer'), ('VENDOR', 'Vendor'), ('EMPLOYEE', 'Employee'), ('JOURNAL', 'Journal Entry'), ('INVOICE', 'Invoice'), ('PAYMENT', 'Payment'), ('ASSET', 'Fixed Asset')], help_text='Business Central entity type', max_length=100)),
                ('bc_id', models.CharField(help_text='Business Central entity ID', max_length=50)),
                ('bc_number', models.CharField(blank=True, help_text='Business Central entity number/code', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sync_errors', models.TextField(blank=True, help_text='Last sync error messages')),
            ],
            options={
                'verbose_name': 'Dynamics Mapping',
                'verbose_name_plural': 'Dynamics Mappings',
                'indexes': [models.Index(fields=['local_model', 'local_id'], name='dynamics_in_local_m_cb4f40_idx'), models.Index(fields=['bc_entity', 'bc_id'], name='dynamics_in_bc_enti_663e6b_idx')],
                'unique_together': {('local_model', 'local_id')},
            },
        ),
        migrations.CreateModel(
            name='SyncQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text='Model that failed to sync', max_length=100)),
                ('object_id', models.CharField(help_text='Primary key of the object', max_length=50)),
                ('sync_type', models.CharField(help_text='Type of sync operation', max_length=50)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('next_retry', models.DateTimeField(default=django.utils.timezone.now)),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'High'), (4, 'Critical')], default=2)),
                ('last_error', models.TextField(blank=True)),
                ('last_attempt', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_processing', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Sync Queue Item',
                'verbose_name_plural': 'Sync Queue',
                'ordering': ['priority', 'next_retry'],
                'indexes': [models.Index(fields=['is_active', 'next_retry'], name='dynamics_in_is_acti_6a2cc1_idx'), models.Index(fields=['model_name', 'object_id'], name='dynamics_in_model_n_211eb7_idx'), models.Index(fields=['priority'], name='dynamics_in_priorit_224a63_idx')],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('TRANSACTION', 'Fuel Transaction'), ('INVENTORY', 'Coupon Inventory'), ('EMPLOYEE', 'Employee Data'), ('VEHICLE', 'Vehicle Asset'), ('FINANCIAL', 'Financial Entry'), ('BULK', 'Bulk Operation')], max_length=50)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING', 'Pending'), ('PARTIAL', 'Partial Success'), ('RETRY', 'Retry Required')], max_length=20)),
                ('message', models.TextField(blank=True, help_text='Sync result message or error details')),
                ('records_processed', models.IntegerField(default=0)),
                ('records_successful', models.IntegerField(default=0)),
                ('records_failed', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('batch_id', models.CharField(blank=True, help_text='Batch identifier for grouped operations', max_length=100)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sync Log',
                'verbose_name_plural': 'Sync Logs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['sync_type', 'status'], name='dynamics_in_sync_ty_6ad908_idx'), models.Index(fields=['started_at'], name='dynamics_in_started_7f97f5_idx'), models.Index(fields=['batch_id'], name='dynamics_in_batch_i_ec6314_idx')],
            },
        ),
    ]
