# Generated by Django for backend model enhancements
# This migration adds missing fields required for frontend functionality

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0001_initial'),
    ]

    # No-op: these fields are now part of the base schema in earlier migrations.
    operations = []
