# Generated by Django 5.0.7 on 2025-08-10 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='barcode',
            field=models.CharField(blank=True, default='', help_text='Barcode for the box (if applicable)', max_length=255),
        ),
        migrations.AddField(
            model_name='box',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='USD to ZWL exchange rate', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='box',
            name='fuel_price_per_litre_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fuel price per litre in USD', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='box',
            name='monetary_value_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total monetary value in USD', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='box',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Additional notes about this box'),
        ),
        migrations.AddField(
            model_name='parliamentsession',
            name='fuel_entitlement_litres',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fuel entitlement in litres for this session', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='parliamentsession',
            name='is_mandatory',
            field=models.BooleanField(default=False, help_text='Whether attendance is mandatory for this session'),
        ),
        migrations.AddField(
            model_name='parliamentsession',
            name='venue',
            field=models.CharField(blank=True, help_text='Venue where the session will be held', max_length=200),
        ),
        migrations.AddField(
            model_name='program',
            name='end_date',
            field=models.DateField(blank=True, help_text='End date of the program', null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='location',
            field=models.CharField(blank=True, help_text='Alternative location field (alias for venue)', max_length=200),
        ),
        migrations.AddField(
            model_name='program',
            name='organizer',
            field=models.ForeignKey(blank=True, help_text='User organizing this program', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_programs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='program',
            name='scheduled_date',
            field=models.DateField(blank=True, help_text='Date when the program is scheduled', null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='sub_center',
            field=models.ForeignKey(blank=True, help_text='SubCenter managing this program', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_programs', to='fuel.subcenter'),
        ),
    ]
