# Generated by Django 5.0.7 on 2025-08-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0002_add_box_notes_barcode_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='first_coupon_number',
            field=models.CharField(blank=True, default='', help_text='First coupon number in the box (e.g., PU00GH355101)', max_length=50),
        ),
        migrations.AlterField(
            model_name='box',
            name='last_coupon_number',
            field=models.CharField(blank=True, default='', help_text='Last coupon number in the box (e.g., PU00GH355200)', max_length=50),
        ),
    ]
