# Generated by Django 5.2 on 2025-08-11 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0004_add_usd_monetary_fields_azure_production'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['-scheduled_date'], 'verbose_name': 'Program', 'verbose_name_plural': 'Programs'},
        ),
        migrations.RemoveField(
            model_name='box',
            name='exchange_rate',
        ),
        migrations.RemoveField(
            model_name='box',
            name='fuel_price_per_litre_usd',
        ),
        migrations.RemoveField(
            model_name='box',
            name='monetary_value_usd',
        ),
        migrations.RemoveField(
            model_name='parliamentsession',
            name='fuel_entitlement_litres',
        ),
        migrations.RemoveField(
            model_name='parliamentsession',
            name='is_mandatory',
        ),
        migrations.RemoveField(
            model_name='parliamentsession',
            name='venue',
        ),
        migrations.RemoveField(
            model_name='program',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='program',
            name='name',
        ),
        migrations.RemoveField(
            model_name='program',
            name='session',
        ),
        migrations.RemoveField(
            model_name='program',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='program',
            name='venue',
        ),
        migrations.AddField(
            model_name='coupondistribution',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_distributions', to='fuel.program'),
        ),
        migrations.AddField(
            model_name='program',
            name='expected_participants',
            field=models.PositiveIntegerField(default=0, help_text='Expected number of participants'),
        ),
        migrations.AddField(
            model_name='program',
            name='fuel_allocation_approved',
            field=models.BooleanField(default=False, help_text='Whether fuel allocation has been approved for this program'),
        ),
        migrations.AddField(
            model_name='program',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the program'),
        ),
        migrations.AddField(
            model_name='program',
            name='title',
            field=models.CharField(default='Untitled Program', help_text='Program title or name', max_length=200),
        ),
        migrations.AlterField(
            model_name='box',
            name='barcode',
            field=models.CharField(blank=True, help_text='Barcode identifier for the box', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='box',
            name='box_code',
            field=models.CharField(help_text='Unique identifier for the box (e.g., FCB-2025-0001)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='box',
            name='first_coupon_number',
            field=models.CharField(help_text='First coupon number in the box (e.g., PU00GH355101)', max_length=50),
        ),
        migrations.AlterField(
            model_name='box',
            name='last_coupon_number',
            field=models.CharField(help_text='Last coupon number in the box (e.g., PU00GH355200)', max_length=50),
        ),
        migrations.AlterField(
            model_name='box',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about this box', null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the program'),
        ),
        migrations.AlterField(
            model_name='program',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='When the program is scheduled to end', null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this program is active/upcoming'),
        ),
        migrations.AlterField(
            model_name='program',
            name='location',
            field=models.CharField(help_text='Program venue or location', max_length=200),
        ),
        migrations.AlterField(
            model_name='program',
            name='organizer',
            field=models.ForeignKey(blank=True, help_text='User responsible for organizing this program', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organized_programs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_type',
            field=models.CharField(choices=[('SESSION', 'Parliament Session'), ('COMMITTEE', 'Committee Meeting'), ('WORKSHOP', 'Workshop/Training'), ('OUTREACH', 'Outreach Program'), ('CONFERENCE', 'Conference'), ('CEREMONY', 'Official Ceremony'), ('INSPECTION', 'Site Inspection'), ('CAMPAIGN', 'Political Campaign'), ('NATIONAL_EVENT', 'National Event'), ('CONSTITUENCY', 'Constituency Visit'), ('DEBATE', 'Parliamentary Debate'), ('BUDGET_SESSION', 'Budget Session'), ('POLICY_MEETING', 'Policy Meeting'), ('PUBLIC_HEARING', 'Public Hearing'), ('DIPLOMATIC', 'Diplomatic Event'), ('OTHER', 'Other Event')], default='SESSION', max_length=20),
        ),
        migrations.AlterField(
            model_name='program',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, help_text='When the program is scheduled to start', null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='sub_center',
            field=models.ForeignKey(blank=True, help_text='Sub-center responsible for this program', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='fuel.subcenter'),
        ),
        migrations.AddIndex(
            model_name='coupondistribution',
            index=models.Index(fields=['program'], name='fuel_coupon_program_38d4c5_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['program_type'], name='fuel_progra_program_6f4d11_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['scheduled_date'], name='fuel_progra_schedul_c74c2f_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['sub_center'], name='fuel_progra_sub_cen_63cd02_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['organizer'], name='fuel_progra_organiz_78db9b_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['is_active'], name='fuel_progra_is_acti_756812_idx'),
        ),
        migrations.AlterModelTable(
            name='program',
            table='fuel_program',
        ),
    ]
