# Generated by Django 5.2 on 2025-08-11 08:01

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0006_field_mapping_consistency'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='book_details_json',
            field=models.JSONField(blank=True, default=list, help_text='Detailed book breakdown from frontend (JSON format)'),
        ),
        migrations.AddField(
            model_name='box',
            name='calculation_mode',
            field=models.CharField(choices=[('first-and-count', 'First Coupon and Count'), ('first-and-last', 'First and Last Coupon'), ('manual', 'Manual Entry')], default='first-and-count', help_text='Method used to calculate coupon numbers', max_length=20),
        ),
        migrations.AddField(
            model_name='box',
            name='exchange_rate_zwg_usd',
            field=models.DecimalField(decimal_places=4, default=Decimal('27.50'), help_text='Exchange rate ZWG to USD', max_digits=8),
        ),
        migrations.AddField(
            model_name='box',
            name='fuel_price_per_litre_usd',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.40'), help_text='Price per litre in USD', max_digits=8),
        ),
        migrations.AddField(
            model_name='box',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('VERIFIED', 'Verified'), ('DISTRIBUTED', 'Distributed'), ('ARCHIVED', 'Archived')], default='RECEIVED', help_text='Current status of the box', max_length=20),
        ),
        migrations.AddField(
            model_name='box',
            name='total_coupons_calculated',
            field=models.IntegerField(default=0, help_text='Total number of coupons calculated from frontend logic'),
        ),
        migrations.AddField(
            model_name='box',
            name='total_value_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total value in USD (calculated from frontend)', max_digits=12),
        ),
        migrations.AddField(
            model_name='box',
            name='total_value_zwg',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total value in ZWG (calculated from frontend)', max_digits=12),
        ),
        migrations.AddField(
            model_name='box',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Notes from verification process', null=True),
        ),
        migrations.AddField(
            model_name='box',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When this box was verified', null=True),
        ),
        migrations.AddField(
            model_name='box',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='User who verified this box', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_boxes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='box',
            name='denomination',
            field=models.IntegerField(choices=[(5, '5 Litres'), (10, '10 Litres'), (20, '20 Litres'), (50, '50 Litres')], default=20, help_text='Litres per coupon (5L, 10L, 20L, or 50L)'),
        ),
        migrations.AlterField(
            model_name='box',
            name='total_litres',
            field=models.DecimalField(decimal_places=2, help_text='Total litres calculated from coupons * denomination', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
