# Generated by Django 5.2 on 2025-08-11 08:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0007_enhance_box_model_with_frontend_calculations'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_code',
            field=models.CharField(blank=True, help_text='Unique book identifier (auto-generated)', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='book',
            name='generated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='When this book was generated/created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='generated_by',
            field=models.ForeignKey(blank=True, help_text='User who generated this book', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Whether this book has been verified for accuracy'),
        ),
        migrations.AddField(
            model_name='book',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Notes from the verification process', null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When this book was verified', null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='User who verified this book', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='digital_signature',
            field=models.TextField(blank=True, help_text='Base64 encoded digital signature image', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='full_address',
            field=models.TextField(blank=True, help_text='Complete address for official documents', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, help_text='National ID number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.TextField(blank=True, help_text='Base64 encoded profile picture', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='signature_uploaded_at',
            field=models.DateTimeField(blank=True, help_text='When the digital signature was uploaded', null=True),
        ),
    ]
