# Generated by Django 5.2 on 2025-08-11 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0008_enhance_book_coupon_tracking'),
    ]

    operations = [
        # No-op migration for centralized book generation
        # Functionality was implemented in later migrations
    ]