# Generated by Django 5.2 on 2025-08-11 16:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0023_fix_coupon_distribution_and_session_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='damage_report',
            field=models.TextField(blank=True, help_text='Report of any damage found during receipt or verification', null=True),
        ),
        migrations.AddField(
            model_name='box',
            name='delivery_note',
            field=models.CharField(blank=True, help_text='Delivery note reference number', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='box',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Invoice reference number for this box', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='box',
            name='qr_code_data',
            field=models.TextField(blank=True, help_text='QR code data for quick identification', null=True),
        ),
        migrations.AddField(
            model_name='box',
            name='received_by_signature',
            field=models.TextField(blank=True, help_text='Digital signature data of person who received the box', null=True),
        ),
        migrations.AddField(
            model_name='box',
            name='received_date',
            field=models.DateField(blank=True, help_text='Date when box was received (extracted from received_at)', null=True),
        ),
        migrations.AddField(
            model_name='box',
            name='received_time',
            field=models.TimeField(blank=True, help_text='Time when box was received (extracted from received_at)', null=True),
        ),
        migrations.AddField(
            model_name='box',
            name='supplier',
            field=models.CharField(blank=True, help_text='Supplier or vendor name', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='box',
            name='coupons_per_book',
            field=models.IntegerField(default=100, help_text='Number of coupons per book (1-100 range, usually 100 pages/coupons)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='box',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Receipt'), ('RECEIVED', 'Received'), ('VERIFIED', 'Verified'), ('DISPATCHED', 'Dispatched'), ('DAMAGED', 'Damaged'), ('ARCHIVED', 'Archived')], default='RECEIVED', help_text='Current status of the box', max_length=20),
        ),
    ]
