# Generated by Django 5.2 on 2025-08-16 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0028_alter_systemalert_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaryprofile',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended'), ('PENDING_APPROVAL', 'Pending Approval')], default='ACTIVE', help_text='Current beneficiary status', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
