# Generated by Django 5.2 on 2025-08-16 05:45

from django.db import migrations


def migrate_vehicle_data(apps, schema_editor):
    HarmonizedBeneficiaryProfile = apps.get_model('fuel', 'HarmonizedBeneficiaryProfile')
    BeneficiaryVehicle = apps.get_model('fuel', 'BeneficiaryVehicle')

    for beneficiary in HarmonizedBeneficiaryProfile.objects.all():
        if beneficiary.vehicle_registration:  # Only migrate if vehicle data exists
            BeneficiaryVehicle.objects.create(
                beneficiary=beneficiary,
                registration=beneficiary.vehicle_registration,
                make=beneficiary.vehicle_make or '',
                model=beneficiary.vehicle_model or '',
                year=beneficiary.vehicle_year or 2000,  # Default if None
                fuel_type=beneficiary.fuel_type or 'PETROL',
                engine_size=beneficiary.engine_size,
                is_active=True
            )


def reverse_migrate_vehicle_data(apps, schema_editor):
    BeneficiaryVehicle = apps.get_model('fuel', 'BeneficiaryVehicle')
    BeneficiaryVehicle.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0031_beneficiaryvehicle'),
    ]

    operations = [
        migrations.RunPython(migrate_vehicle_data, reverse_migrate_vehicle_data),
    ]
