# Generated by Django 5.2 on 2025-08-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0032_migrate_existing_vehicle_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiaryprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='beneficiaryprofile',
            name='chassis_number',
        ),
        migrations.RemoveField(
            model_name='beneficiaryprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='beneficiaryprofile',
            name='engine_number',
        ),
        migrations.RemoveField(
            model_name='beneficiaryprofile',
            name='parliamentary_id',
        ),
        migrations.RemoveField(
            model_name='beneficiaryprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='beneficiaryprofile',
            name='term_end_date',
        ),
        migrations.RemoveField(
            model_name='beneficiaryprofile',
            name='term_start_date',
        ),
        migrations.RemoveField(
            model_name='beneficiaryprofile',
            name='vehicle_color',
        ),
        migrations.AddField(
            model_name='beneficiaryprofile',
            name='party_affiliation',
            field=models.CharField(blank=True, help_text='Political party affiliation', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='BeneficiaryVehicle',
        ),
    ]
