# Generated by Django 5.2 on 2025-08-16 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0033_add_party_affiliation_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='parliamentsession',
            name='end_time',
            field=models.TimeField(default='17:00:00', help_text='Session end time'),
        ),
        migrations.AddField(
            model_name='parliamentsession',
            name='program',
            field=models.ForeignKey(blank=True, help_text='Program this session belongs to (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parliament_sessions', to='fuel.program'),
        ),
        migrations.AddField(
            model_name='parliamentsession',
            name='start_time',
            field=models.TimeField(default='09:00:00', help_text='Session start time'),
        ),
    ]
