# Generated by Django 5.2 on 2025-08-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0034_add_time_and_program_to_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='parliamentsession',
            name='is_mandatory',
            field=models.BooleanField(default=False, help_text='Whether attendance at this session is mandatory'),
        ),
    ]
