# Generated by Django 5.0.7 on 2025-08-18 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0037_add_session_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcenter',
            name='capacity',
            field=models.IntegerField(blank=True, help_text='Maximum capacity for beneficiaries/operations', null=True),
        ),
    ]
