# Generated by Django on 2025-08-19 for MainCenter frontend alignment

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0038_subcenter_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcenter',
            name='contact_number',
            field=models.CharField(blank=True, help_text='Primary contact phone number for the sub-center', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subcenter',
            name='email',
            field=models.EmailField(blank=True, help_text='Primary email address for the sub-center', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='box',
            name='is_received',
            field=models.BooleanField(default=True, help_text='Whether this box has been received (calculated from status or explicit)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='fuel_users', related_query_name='fuel_user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='fuel_users', related_query_name='fuel_user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]