# Generated by Django 5.0.7 on 2025-08-20 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '10006_enhance_dispatch_pages_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookdispatch',
            name='books',
        ),
        migrations.RemoveField(
            model_name='bookdispatch',
            name='first_serial',
        ),
        migrations.RemoveField(
            model_name='bookdispatch',
            name='last_serial',
        ),
        migrations.RemoveField(
            model_name='bookdispatch',
            name='pages',
        ),
        migrations.RemoveField(
            model_name='bookdispatch',
            name='total_coupons',
        ),
        migrations.RemoveField(
            model_name='bookdispatch',
            name='total_value_usd',
        ),
        migrations.AlterField(
            model_name='bookdispatch',
            name='dispatched_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatches_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookdispatch',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatches_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookdispatch',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DISPATCHED', 'Dispatched'), ('RECEIVED', 'Received')], default='PENDING', max_length=20),
        ),
        migrations.DeleteModel(
            name='HarmonizedBeneficiaryProfile',
        ),
    ]
