# Generated by Django 5.2 on 2025-08-20 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '10008_add_inventory_tracking_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='verification_checks',
            field=models.JSONField(blank=True, default=list, help_text='Verification checklist items completed for this book'),
        ),
        migrations.AddField(
            model_name='box',
            name='sign_off_date',
            field=models.DateTimeField(blank=True, help_text='When this box was signed off', null=True),
        ),
        migrations.AddField(
            model_name='box',
            name='sign_off_notes',
            field=models.TextField(blank=True, help_text='Notes from sign-off process', null=True),
        ),
        migrations.AddField(
            model_name='box',
            name='signed_off_by',
            field=models.ForeignKey(blank=True, help_text='User who signed off on this box', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_off_boxes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='box',
            name='verification_checks',
            field=models.JSONField(blank=True, default=list, help_text='Verification checklist items completed'),
        ),
    ]
