# Generated by Django 4.2.15 on 2025-08-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '10015_remove_book_total_coupons_remove_coupon_fuel_type_and_more'),
    ]

    operations = [
        # This migration intentionally left empty to prevent auto-generation
        # All necessary schema changes are already handled by previous migrations
    ]
