# Generated by Django 4.2.15 on 2025-08-31 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '10014_add_centralized_generation_fields'),
    ]

    operations = [
        # No-op migration - field already exists with correct configuration
        # This migration was originally trying to alter fields that were already properly configured
    ]
