# Generated by Django 4.2.15 on 2025-08-31 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '10014_add_centralized_generation_fields'),
    ]

    operations = [
        # Only update the coupon_serial field to have a proper default for PostgreSQL
        migrations.AlterField(
            model_name='coupon',
            name='coupon_serial',
            field=models.CharField(blank=True, default='NOT_PROVIDED', help_text='Unique coupon serial (e.g., PU006H1355101 - PetroTrade format)', max_length=50),
        ),
    ]
