# Generated by Django 5.2 on 2025-08-30 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '10011_alter_harmonizedbeneficiaryprofile_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdispatch',
            name='books',
            field=models.ManyToManyField(blank=True, help_text='Books included in this dispatch', related_name='dispatches', to='fuel.book'),
        ),
        migrations.AddField(
            model_name='bookdispatch',
            name='first_serial',
            field=models.CharField(blank=True, help_text='First coupon serial in this dispatch', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bookdispatch',
            name='last_serial',
            field=models.CharField(blank=True, help_text='Last coupon serial in this dispatch', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bookdispatch',
            name='total_coupons',
            field=models.IntegerField(default=0, help_text='Total number of coupons in this dispatch'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERUSER', 'Super User (Developer)'), ('ADMIN', 'System Administrator'), ('MAIN_CENTER', 'Main Center Officer'), ('SUB_CENTER', 'Sub Center Officer'), ('BENEFICIARY', 'Beneficiary'), ('AUDITOR', 'Auditor'), ('MAIN_CENTER_APPROVER', 'Main Center Approver'), ('SUB_CENTER_APPROVER', 'Sub Center Approver'), ('SERGEANT_OF_ARMS', 'Sergeant of Arms')], default='BENEFICIARY', max_length=20),
        ),
    ]
