# Generated by Django 5.2 on 2025-08-30 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '10012_bookdispatch_books_bookdispatch_first_serial_and_more'),
    ]

    operations = [
        # Ensure the books ManyToMany field exists (idempotent operation)
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS fuel_bookdispatch_books (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                bookdispatch_id INTEGER NOT NULL,
                book_id INTEGER NOT NULL,
                FOREIGN KEY (bookdispatch_id) REFERENCES fuel_bookdispatch (id),
                FOREIGN KEY (book_id) REFERENCES fuel_book (id),
                UNIQUE (bookdispatch_id, book_id)
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS fuel_bookdispatch_books;"
        ),
    ]
