# Generated by Django 5.2 on 2025-08-28 16:11

import django.utils.timezone
import model_utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '10010_add_harmonized_beneficiary_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harmonizedbeneficiaryprofile',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='harmonizedbeneficiaryprofile',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
    ]
