# Generated by Django 5.2 on 2025-09-01 11:42

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '10017_merge_20250901_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticalParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('abbreviation', models.CharField(help_text='Party abbreviation (e.g., ZANU-PF, MDC, CCC)', max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('founded_date', models.DateField(blank=True, null=True)),
                ('leader_name', models.CharField(blank=True, max_length=200)),
                ('party_color', models.CharField(blank=True, help_text='Party color in hex format (e.g., #FF0000)', max_length=7)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the party is currently active in Parliament')),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Political Party',
                'verbose_name_plural': 'Political Parties',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='beneficiaryprofile',
            name='political_party',
            field=models.ForeignKey(blank=True, help_text='Political party affiliation', null=True, on_delete=django.db.models.deletion.SET_NULL, to='fuel.politicalparty'),
        ),
    ]
