# Generated by Django 4.1.13 on 2025-09-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '10018_politicalparty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaryprofile',
            name='party_affiliation',
            field=models.CharField(max_length=100, blank=True, default=''),
        ),
        migrations.RunSQL(
            sql=(
                "UPDATE fuel_beneficiaryprofile SET party_affiliation = '' WHERE party_affiliation IS NULL;"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
