# Generated by Django 5.2 on 2025-09-01 11:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import fuel.validators
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '10017_merge_20250901_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticalParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('abbreviation', models.CharField(help_text='Party abbreviation (e.g., ZANU-PF, MDC, CCC)', max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('founded_date', models.DateField(blank=True, null=True)),
                ('leader_name', models.CharField(blank=True, max_length=200)),
                ('party_color', models.CharField(blank=True, help_text='Party color in hex format (e.g., #FF0000)', max_length=7)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the party is currently active in Parliament')),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Political Party',
                'verbose_name_plural': 'Political Parties',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='beneficiaryprofile',
            name='party_affiliation',
        ),
        migrations.RemoveField(
            model_name='book',
            name='total_coupons',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='is_used',
        ),
        migrations.AlterField(
            model_name='book',
            name='first_coupon_number',
            field=models.CharField(blank=True, help_text='DEPRECATED: Use first_coupon_serial instead', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='first_coupon_serial',
            field=models.CharField(blank=True, help_text='First coupon serial in this book (e.g., PU006H1355101)', max_length=50, null=True, validators=[fuel.validators.validate_petrotrade_serial]),
        ),
        migrations.AlterField(
            model_name='book',
            name='last_coupon_number',
            field=models.CharField(blank=True, help_text='DEPRECATED: Use last_coupon_number instead', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='last_coupon_serial',
            field=models.CharField(blank=True, help_text='Last coupon serial in this book (e.g., PU006H1355200)', max_length=50, null=True, validators=[fuel.validators.validate_petrotrade_serial]),
        ),
        migrations.AlterField(
            model_name='box',
            name='coupons_per_book',
            field=models.IntegerField(default=100, help_text='Number of coupons per book (1-100 range, usually 100 pages/coupons)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='box',
            name='first_coupon_number',
            field=models.CharField(blank=True, help_text='DEPRECATED: Use first_coupon_serial instead', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='box',
            name='first_coupon_serial',
            field=models.CharField(blank=True, help_text='First coupon serial in the box (e.g., PU006H1355101)', max_length=50, null=True, validators=[fuel.validators.validate_petrotrade_serial]),
        ),
        migrations.AlterField(
            model_name='box',
            name='last_coupon_number',
            field=models.CharField(blank=True, help_text='DEPRECATED: Use last_coupon_serial instead', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='box',
            name='last_coupon_serial',
            field=models.CharField(blank=True, help_text='Last coupon serial in the box (e.g., PU006H1356100)', max_length=50, null=True, validators=[fuel.validators.validate_petrotrade_serial]),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_number',
            field=models.CharField(blank=True, help_text='DEPRECATED: Use coupon_serial instead', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_serial',
            field=models.CharField(db_index=True, help_text='Unique coupon serial (e.g., PU006H1355101 - PetroTrade format)', max_length=50, unique=True, validators=[fuel.validators.validate_petrotrade_serial]),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='serial_number',
            field=models.CharField(blank=True, help_text='DEPRECATED: Additional serial number', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='beneficiaryprofile',
            name='political_party',
            field=models.ForeignKey(blank=True, help_text='Political party affiliation', null=True, on_delete=django.db.models.deletion.SET_NULL, to='fuel.politicalparty'),
        ),
    ]
