# Generated by Django 5.2 on 2025-09-01 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0009_centralized_book_generation'),
        ('fuel', '10016_remove_book_total_coupons_remove_coupon_fuel_type_and_more'),
    ]

    operations = [
    ]
