# Generated by Django 5.2 on 2025-09-20 22:37

import django.db.models.deletion
import django.utils.timezone
import fuel.validators
from django.conf import settings
from django.db import migrations, models, connection


def check_column_exists(table_name, column_name):
    """Check if a column exists in a table"""
    with connection.cursor() as cursor:
        # Different query for SQLite vs PostgreSQL
        if connection.vendor == 'sqlite':
            cursor.execute(f"PRAGMA table_info({table_name})")
            columns = [column[1] for column in cursor.fetchall()]
            return column_name in columns
        else:  # PostgreSQL
            cursor.execute("""
                SELECT COUNT(*) 
                FROM information_schema.columns 
                WHERE table_name = %s AND column_name = %s
            """, [table_name, column_name])
            return cursor.fetchone()[0] > 0


def safe_add_field(apps, schema_editor, model_name, field_name, field):
    """Safely add a field only if it doesn't exist"""
    table_name = f"fuel_{model_name.lower()}"
    
    # Check for ForeignKey fields which create _id columns
    db_column_name = field_name
    if hasattr(field, 'remote_field') and field.remote_field:
        db_column_name = f"{field_name}_id"
    
    if not check_column_exists(table_name, db_column_name):
        # Field doesn't exist, safe to add
        model = apps.get_model('fuel', model_name)
        # Create a new field instance to avoid state conflicts
        field_copy = field.__class__(**{
            k: v for k, v in field.__dict__.items() 
            if k not in ['creation_counter', 'model', 'name']
        })
        field_copy.set_attributes_from_name(field_name)
        schema_editor.add_field(model, field_copy)
        print(f"Added field {field_name} to {model_name}")
    else:
        print(f"Field {field_name} already exists in {model_name}, skipping")


def safe_remove_field(apps, schema_editor, model_name, field_name):
    """Safely remove a field only if it exists"""
    table_name = f"fuel_{model_name.lower()}"
    if check_column_exists(table_name, field_name):
        # Field exists, safe to remove
        model = apps.get_model('fuel', model_name)
        field = model._meta.get_field(field_name)
        schema_editor.remove_field(model, field)
        print(f"Removed field {field_name} from {model_name}")
    else:
        print(f"Field {field_name} doesn't exist in {model_name}, skipping")


def add_book_fields_safely(apps, schema_editor):
    """Safely add fields to Book model"""
    safe_add_field(apps, schema_editor, 'Book', 'first_coupon_serial', 
                   models.CharField(blank=True, help_text='First coupon serial in this book (e.g., PU006H1355101)', max_length=50, null=True, validators=[fuel.validators.validate_petrotrade_serial]))
    safe_add_field(apps, schema_editor, 'Book', 'last_coupon_serial', 
                   models.CharField(blank=True, help_text='Last coupon serial in this book (e.g., PU006H1355200)', max_length=50, null=True, validators=[fuel.validators.validate_petrotrade_serial]))
    safe_add_field(apps, schema_editor, 'Book', 'is_generated',
                   models.BooleanField(default=False, help_text='Whether this book was generated via the centralized service'))


def add_box_fields_safely(apps, schema_editor):
    """Safely add fields to Box model"""
    safe_add_field(apps, schema_editor, 'Box', 'first_coupon_serial',
                   models.CharField(blank=True, help_text='First coupon serial in the box (e.g., PU006H1355101)', max_length=50, null=True, validators=[fuel.validators.validate_petrotrade_serial]))
    safe_add_field(apps, schema_editor, 'Box', 'last_coupon_serial',
                   models.CharField(blank=True, help_text='Last coupon serial in the box (e.g., PU006H1356100)', max_length=50, null=True, validators=[fuel.validators.validate_petrotrade_serial]))
    safe_add_field(apps, schema_editor, 'Box', 'total_books',
                   models.IntegerField(blank=True, help_text='Total number of books that will be generated for this box', null=True))


def add_coupon_fields_safely(apps, schema_editor):
    """Safely add fields to Coupon model"""
    safe_add_field(apps, schema_editor, 'Coupon', 'coupon_serial',
                   models.CharField(db_index=True, default='TEMP_SERIAL', help_text='Unique coupon serial (e.g., PU006H1355101 - PetroTrade format)', max_length=50, unique=True, validators=[fuel.validators.validate_petrotrade_serial]))
    safe_add_field(apps, schema_editor, 'Coupon', 'coupon_value',
                   models.IntegerField(default=20, help_text='Fuel denomination in litres'))
    safe_add_field(apps, schema_editor, 'Coupon', 'page_number',
                   models.IntegerField(blank=True, help_text='Page number within the book (1-based)', null=True))


def remove_book_fields_safely(apps, schema_editor):
    """Safely remove fields from Book model"""
    safe_remove_field(apps, schema_editor, 'Book', 'is_generated')
    safe_remove_field(apps, schema_editor, 'Book', 'last_coupon_serial')
    safe_remove_field(apps, schema_editor, 'Book', 'first_coupon_serial')


def remove_box_fields_safely(apps, schema_editor):
    """Safely remove fields from Box model"""
    safe_remove_field(apps, schema_editor, 'Box', 'total_books')
    safe_remove_field(apps, schema_editor, 'Box', 'last_coupon_serial')
    safe_remove_field(apps, schema_editor, 'Box', 'first_coupon_serial')


def remove_coupon_fields_safely(apps, schema_editor):
    """Safely remove fields from Coupon model"""
    safe_remove_field(apps, schema_editor, 'Coupon', 'page_number')
    safe_remove_field(apps, schema_editor, 'Coupon', 'coupon_value')
    safe_remove_field(apps, schema_editor, 'Coupon', 'coupon_serial')


def add_fuelentitlement_fields_safely(apps, schema_editor):
    """Safely add fields to FuelEntitlement model"""
    User = apps.get_model('auth', 'User')
    
    safe_add_field(apps, schema_editor, 'FuelEntitlement', 'approved_by',
                   models.ForeignKey(blank=True, help_text='User who approved this entitlement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entitlements_approved', to='auth.User'))
    safe_add_field(apps, schema_editor, 'FuelEntitlement', 'approved_date',
                   models.DateTimeField(blank=True, help_text='Date when entitlement was approved', null=True))
    safe_add_field(apps, schema_editor, 'FuelEntitlement', 'created_by',
                   models.ForeignKey(blank=True, help_text='User who created this entitlement record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entitlements_created', to='auth.User'))
    safe_add_field(apps, schema_editor, 'FuelEntitlement', 'entitlement_type',
                   models.CharField(choices=[('MONTHLY', 'Monthly Entitlement'), ('SESSION', 'Parliament Session'), ('COMMITTEE', 'Committee Meeting'), ('SPECIAL_EVENT', 'Special Event'), ('TRAVEL_ALLOWANCE', 'Travel Allowance'), ('EMERGENCY', 'Emergency Allocation'), ('CONSTITUENCY_WORK', 'Constituency Work')], default='MONTHLY', help_text='Type of entitlement', max_length=20))
    safe_add_field(apps, schema_editor, 'FuelEntitlement', 'justification',
                   models.TextField(blank=True, default='', help_text='Justification for this entitlement'))
    safe_add_field(apps, schema_editor, 'FuelEntitlement', 'litres_allocated',
                   models.DecimalField(decimal_places=2, default=0, help_text='Amount of fuel actually allocated/given', max_digits=8))
    safe_add_field(apps, schema_editor, 'FuelEntitlement', 'litres_entitled',
                   models.DecimalField(decimal_places=2, default=200, help_text='Amount of fuel entitled in litres', max_digits=8))
    safe_add_field(apps, schema_editor, 'FuelEntitlement', 'notes',
                   models.TextField(blank=True, help_text='Additional notes about this entitlement'))
    safe_add_field(apps, schema_editor, 'FuelEntitlement', 'period_end',
                   models.DateField(blank=True, help_text='End date of entitlement period', null=True))
    safe_add_field(apps, schema_editor, 'FuelEntitlement', 'period_start',
                   models.DateField(blank=True, help_text='Start date of entitlement period', null=True))
    safe_add_field(apps, schema_editor, 'FuelEntitlement', 'session',
                   models.ForeignKey(blank=True, help_text='Parliament session this entitlement is for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_entitlements', to='fuel.ParliamentSession'))
    safe_add_field(apps, schema_editor, 'FuelEntitlement', 'status',
                   models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PARTIALLY_USED', 'Partially Used'), ('FULLY_USED', 'Fully Used'), ('EXPIRED', 'Expired')], default='PENDING', help_text='Status of the entitlement', max_length=20))


def remove_fuelentitlement_fields_safely(apps, schema_editor):
    """Safely remove fields from FuelEntitlement model"""
    safe_remove_field(apps, schema_editor, 'FuelEntitlement', 'status')
    safe_remove_field(apps, schema_editor, 'FuelEntitlement', 'session')
    safe_remove_field(apps, schema_editor, 'FuelEntitlement', 'period_start')
    safe_remove_field(apps, schema_editor, 'FuelEntitlement', 'period_end')
    safe_remove_field(apps, schema_editor, 'FuelEntitlement', 'notes')
    safe_remove_field(apps, schema_editor, 'FuelEntitlement', 'litres_entitled')
    safe_remove_field(apps, schema_editor, 'FuelEntitlement', 'litres_allocated')
    safe_remove_field(apps, schema_editor, 'FuelEntitlement', 'justification')
    safe_remove_field(apps, schema_editor, 'FuelEntitlement', 'entitlement_type')
    safe_remove_field(apps, schema_editor, 'FuelEntitlement', 'created_by')
    safe_remove_field(apps, schema_editor, 'FuelEntitlement', 'approved_date')
    safe_remove_field(apps, schema_editor, 'FuelEntitlement', 'approved_by')


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '10021_merge_20250904_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuelentitlement',
            name='entitlement_amount',
        ),
        migrations.RunPython(add_book_fields_safely, remove_book_fields_safely),
        migrations.AddField(
            model_name='bookdispatch',
            name='courier_service',
            field=models.CharField(blank=True, help_text='Courier service used', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookdispatch',
            name='delivery_note',
            field=models.CharField(blank=True, help_text='Delivery note or reference', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bookdispatch',
            name='driver_name',
            field=models.CharField(blank=True, help_text="Driver's name", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookdispatch',
            name='driver_phone',
            field=models.CharField(blank=True, help_text="Driver's phone number", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bookdispatch',
            name='generation_mode',
            field=models.CharField(blank=True, help_text='Mode used for coupon generation', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bookdispatch',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional dispatch notes', null=True),
        ),
        migrations.AddField(
            model_name='bookdispatch',
            name='received_date',
            field=models.DateTimeField(blank=True, help_text='Date and time when dispatch was received', null=True),
        ),
        migrations.AddField(
            model_name='bookdispatch',
            name='receiver_signature',
            field=models.TextField(blank=True, help_text='Digital signature or confirmation', null=True),
        ),
        migrations.AddField(
            model_name='bookdispatch',
            name='special_instructions',
            field=models.TextField(blank=True, help_text='Special handling instructions', null=True),
        ),
        migrations.AddField(
            model_name='bookdispatch',
            name='tracking_number',
            field=models.CharField(blank=True, help_text='Tracking number for shipment', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bookdispatch',
            name='transport_method',
            field=models.CharField(blank=True, help_text='Method of transport', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bookdispatch',
            name='vehicle_number',
            field=models.CharField(blank=True, help_text='Vehicle registration number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bookdispatch',
            name='verification_checks',
            field=models.JSONField(blank=True, default=list, help_text='List of verification checks performed'),
        ),
        migrations.AddField(
            model_name='bookdispatch',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Notes from verification process', null=True),
        ),
        migrations.AddField(
            model_name='bookdispatch',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='Date and time of verification', null=True),
        ),
        migrations.AddField(
            model_name='bookdispatch',
            name='verified_by',
            field=models.CharField(blank=True, help_text='Person who verified the dispatch', max_length=100, null=True),
        ),
        migrations.RunPython(add_box_fields_safely, remove_box_fields_safely),
        migrations.RunPython(add_coupon_fields_safely, remove_coupon_fields_safely),
        migrations.RunPython(add_fuelentitlement_fields_safely, remove_fuelentitlement_fields_safely),
        migrations.AlterField(
            model_name='beneficiaryprofile',
            name='party_affiliation',
            field=models.CharField(blank=True, default='', help_text='Political party affiliation (legacy string field)', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='first_coupon_number',
            field=models.CharField(blank=True, help_text='DEPRECATED: Use first_coupon_serial instead', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='last_coupon_number',
            field=models.CharField(blank=True, help_text='DEPRECATED: Use last_coupon_number instead', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='box',
            name='first_coupon_number',
            field=models.CharField(blank=True, help_text='DEPRECATED: Use first_coupon_serial instead', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='box',
            name='last_coupon_number',
            field=models.CharField(blank=True, help_text='DEPRECATED: Use last_coupon_serial instead', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_number',
            field=models.CharField(blank=True, help_text='DEPRECATED: Use coupon_serial instead', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='serial_number',
            field=models.CharField(blank=True, help_text='DEPRECATED: Additional serial number', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='fuelentitlement',
            name='beneficiary',
            field=models.ForeignKey(help_text='Parliament member or staff entitled to fuel', limit_choices_to={'role': 'BENEFICIARY'}, on_delete=django.db.models.deletion.CASCADE, related_name='fuel_entitlements', to=settings.AUTH_USER_MODEL),
        ),
    ]
