# Generated by Django 5.2 on 2025-09-02 13:16

import django.db.models.deletion
import fuel.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '10019_add_party_affiliation_backfill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fuelentitlement',
            options={'ordering': ['-created'], 'verbose_name': 'Fuel Entitlement', 'verbose_name_plural': 'Fuel Entitlements'},
        ),
        migrations.RemoveField(
            model_name='fuelentitlement',
            name='entitlement_amount',
        ),
        migrations.AddField(
            model_name='book',
            name='first_coupon_serial',
            field=models.CharField(blank=True, help_text='First coupon serial in this book (e.g., PU006H1355101)', max_length=50, null=True, validators=[fuel.validators.validate_petrotrade_serial]),
        ),
        migrations.AddField(
            model_name='book',
            name='is_generated',
            field=models.BooleanField(default=False, help_text='Whether this book was generated via the centralized service'),
        ),
        migrations.AddField(
            model_name='book',
            name='last_coupon_serial',
            field=models.CharField(blank=True, help_text='Last coupon serial in this book (e.g., PU006H1355200)', max_length=50, null=True, validators=[fuel.validators.validate_petrotrade_serial]),
        ),
        migrations.AddField(
            model_name='box',
            name='first_coupon_serial',
            field=models.CharField(blank=True, help_text='First coupon serial in the box (e.g., PU006H1355101)', max_length=50, null=True, validators=[fuel.validators.validate_petrotrade_serial]),
        ),
        migrations.AddField(
            model_name='box',
            name='last_coupon_serial',
            field=models.CharField(blank=True, help_text='Last coupon serial in the box (e.g., PU006H1356100)', max_length=50, null=True, validators=[fuel.validators.validate_petrotrade_serial]),
        ),
        migrations.AddField(
            model_name='box',
            name='total_books',
            field=models.IntegerField(blank=True, help_text='Total number of books that will be generated for this box', null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='coupon_serial',
            field=models.CharField(db_index=True, default=1, help_text='Unique coupon serial (e.g., PU006H1355101 - PetroTrade format)', max_length=50, unique=True, validators=[fuel.validators.validate_petrotrade_serial]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='coupon_value',
            field=models.IntegerField(default=20, help_text='Fuel denomination in litres'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='page_number',
            field=models.IntegerField(blank=True, help_text='Page number within the book (1-based)', null=True),
        ),
        migrations.AddField(
            model_name='fuelentitlement',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='User who approved this entitlement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entitlements_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fuelentitlement',
            name='approved_date',
            field=models.DateTimeField(blank=True, help_text='Date when entitlement was approved', null=True),
        ),
        migrations.AddField(
            model_name='fuelentitlement',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this entitlement record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entitlements_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fuelentitlement',
            name='entitlement_type',
            field=models.CharField(choices=[('MONTHLY', 'Monthly Entitlement'), ('SESSION', 'Parliament Session'), ('COMMITTEE', 'Committee Meeting'), ('SPECIAL_EVENT', 'Special Event'), ('TRAVEL_ALLOWANCE', 'Travel Allowance'), ('EMERGENCY', 'Emergency Allocation'), ('CONSTITUENCY_WORK', 'Constituency Work')], default='MONTHLY', help_text='Type of entitlement', max_length=20),
        ),
        migrations.AddField(
            model_name='fuelentitlement',
            name='justification',
            field=models.TextField(blank=True, default='', help_text='Justification for this entitlement'),
        ),
        migrations.AddField(
            model_name='fuelentitlement',
            name='litres_allocated',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount of fuel actually allocated/given', max_digits=8),
        ),
        migrations.AddField(
            model_name='fuelentitlement',
            name='litres_entitled',
            field=models.DecimalField(decimal_places=2, default=200, help_text='Amount of fuel entitled in litres', max_digits=8),
        ),
        migrations.AddField(
            model_name='fuelentitlement',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about this entitlement'),
        ),
        migrations.AddField(
            model_name='fuelentitlement',
            name='period_end',
            field=models.DateField(blank=True, help_text='End date of entitlement period', null=True),
        ),
        migrations.AddField(
            model_name='fuelentitlement',
            name='period_start',
            field=models.DateField(blank=True, help_text='Start date of entitlement period', null=True),
        ),
        migrations.AddField(
            model_name='fuelentitlement',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Related parliament session (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_entitlements', to='fuel.parliamentsession'),
        ),
        migrations.AddField(
            model_name='fuelentitlement',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('ALLOCATED', 'Allocated'), ('PARTIALLY_ALLOCATED', 'Partially Allocated'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='beneficiaryprofile',
            name='party_affiliation',
            field=models.CharField(blank=True, default='', help_text='Political party affiliation (legacy string field)', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='first_coupon_number',
            field=models.CharField(blank=True, help_text='DEPRECATED: Use first_coupon_serial instead', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='last_coupon_number',
            field=models.CharField(blank=True, help_text='DEPRECATED: Use last_coupon_number instead', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='box',
            name='first_coupon_number',
            field=models.CharField(blank=True, help_text='DEPRECATED: Use first_coupon_serial instead', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='box',
            name='last_coupon_number',
            field=models.CharField(blank=True, help_text='DEPRECATED: Use last_coupon_serial instead', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_number',
            field=models.CharField(blank=True, help_text='DEPRECATED: Use coupon_serial instead', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='serial_number',
            field=models.CharField(blank=True, help_text='DEPRECATED: Additional serial number', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='fuelentitlement',
            name='beneficiary',
            field=models.ForeignKey(help_text='Parliament member or staff entitled to fuel', limit_choices_to={'role': 'BENEFICIARY'}, on_delete=django.db.models.deletion.CASCADE, related_name='fuel_entitlements', to=settings.AUTH_USER_MODEL),
        ),
    ]
