# Generated by Django 5.2 on 2025-09-22 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '10018_add_main_center_dispatch_number'),
        ('fuel', '10024_add_main_center_dispatch_number_and_metrics'),
        ('fuel', '10026_merge_20250922_0000'),
    ]

    operations = [
    ]
