# Generated by Django 4.1.13 on 2025-09-04 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '10013_comprehensive_dispatch_tracking_models'),
        ('fuel', '10020_safe_add_fields'),
    ]

    operations = [
    ]
