# Generated by Django 5.2 on 2025-09-22 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '10018_bookdispatch_main_center_dispatch_number'),
        ('fuel', '10027_merge_20250922_0335'),
    ]

    operations = [
    ]
