# Generated by Django 5.2 on 2025-09-26 09:44

import django.db.models.deletion
import django.utils.timezone
import fuel.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '10032_dispatch_aggregates_repair'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaryprofile',
            name='sub_center',
            field=models.ForeignKey(blank=True, help_text='Sub-center this beneficiary is assigned to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiaries', to='fuel.subcenter'),
        ),
        migrations.AddField(
            model_name='book',
            name='first_coupon_serial',
            field=models.CharField(blank=True, help_text='First coupon serial in this book (e.g., PU006H1355101)', max_length=50, null=True, validators=[fuel.validators.validate_petrotrade_serial]),
        ),
        migrations.AddField(
            model_name='book',
            name='is_generated',
            field=models.BooleanField(default=False, help_text='Whether this book was generated via the centralized service'),
        ),
        migrations.AddField(
            model_name='book',
            name='last_coupon_serial',
            field=models.CharField(blank=True, help_text='Last coupon serial in this book (e.g., PU006H1355200)', max_length=50, null=True, validators=[fuel.validators.validate_petrotrade_serial]),
        ),
        migrations.AddField(
            model_name='bookdispatch',
            name='main_center_dispatch_number',
            field=models.CharField(blank=True, help_text='Primary sequential number for Main Center tracking (auto-generated)', max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='box',
            name='first_coupon_serial',
            field=models.CharField(blank=True, help_text='First coupon serial in the box (e.g., PU006H1355101)', max_length=50, null=True, validators=[fuel.validators.validate_petrotrade_serial]),
        ),
        migrations.AddField(
            model_name='box',
            name='last_coupon_serial',
            field=models.CharField(blank=True, help_text='Last coupon serial in the box (e.g., PU006H1356100)', max_length=50, null=True, validators=[fuel.validators.validate_petrotrade_serial]),
        ),
        migrations.AddField(
            model_name='box',
            name='total_books',
            field=models.IntegerField(blank=True, help_text='Total number of books that will be generated for this box', null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='coupon_serial',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, help_text='Unique coupon serial (e.g., PU006H1355101 - PetroTrade format)', max_length=50, unique=True, validators=[fuel.validators.validate_petrotrade_serial]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='coupon_value',
            field=models.IntegerField(default=20, help_text='Fuel denomination in litres'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='page_number',
            field=models.IntegerField(blank=True, help_text='Page number within the book (1-based)', null=True),
        ),
        migrations.AddField(
            model_name='couponhandover',
            name='approved_by',
            field=models.CharField(blank=True, help_text='Approver for override/emergency', max_length=100),
        ),
        migrations.AddField(
            model_name='couponhandover',
            name='authorization_letter',
            field=models.TextField(blank=True, help_text='Authorization letter details'),
        ),
        migrations.AddField(
            model_name='couponhandover',
            name='based_on_entitlement',
            field=models.BooleanField(default=True, help_text='Whether handover is based on entitlement'),
        ),
        migrations.AddField(
            model_name='couponhandover',
            name='beneficiary_signature',
            field=models.TextField(blank=True, help_text='Base64 encoded beneficiary signature'),
        ),
        migrations.AddField(
            model_name='couponhandover',
            name='coupons',
            field=models.ManyToManyField(help_text='Coupons included in this handover', related_name='handovers', to='fuel.coupon'),
        ),
        migrations.AddField(
            model_name='couponhandover',
            name='delivery_note',
            field=models.CharField(blank=True, help_text='Delivery note or reference', max_length=200),
        ),
        migrations.AddField(
            model_name='couponhandover',
            name='emergency_reason',
            field=models.TextField(blank=True, help_text='Reason for emergency allocation'),
        ),
        migrations.AddField(
            model_name='couponhandover',
            name='entitlement_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Entitlement amount', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='couponhandover',
            name='first_serial',
            field=models.CharField(blank=True, help_text='First coupon serial in handover', max_length=50),
        ),
        migrations.AddField(
            model_name='couponhandover',
            name='handed_over_by',
            field=models.ForeignKey(blank=True, help_text='User who performed the handover', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='couponhandover',
            name='handed_over_date',
            field=models.DateField(blank=True, help_text='Actual handover date', null=True),
        ),
        migrations.AddField(
            model_name='couponhandover',
            name='handed_over_time',
            field=models.TimeField(blank=True, help_text='Actual handover time', null=True),
        ),
        migrations.AddField(
            model_name='couponhandover',
            name='handover_document',
            field=models.TextField(blank=True, help_text='Handover document details'),
        ),
        migrations.AddField(
            model_name='couponhandover',
            name='handover_id',
            field=models.CharField(default=django.utils.timezone.now, help_text='Unique handover identifier', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='couponhandover',
            name='handover_location',
            field=models.CharField(blank=True, help_text='Location where handover took place', max_length=200),
        ),
        migrations.AddField(
            model_name='couponhandover',
            name='handover_method',
            field=models.CharField(choices=[('DIRECT_PICKUP', 'Direct Pickup'), ('OFFICE_DELIVERY', 'Office Delivery'), ('COURIER', 'Courier Service'), ('REPRESENTATIVE', 'Authorized Representative')], default='DIRECT_PICKUP', help_text='Method of handover', max_length=30),
        ),
        migrations.AddField(
            model_name='couponhandover',
            name='handover_mode',
            field=models.CharField(choices=[('entitlement-based', 'Entitlement-Based Handover'), ('serial-range', 'Serial Range Handover'), ('quantity-based', 'Quantity-Based Handover'), ('emergency-allocation', 'Emergency Allocation')], default='entitlement-based', help_text='Intelligent generation mode used', max_length=50),
        ),
        migrations.AddField(
            model_name='couponhandover',
            name='handover_notes',
            field=models.TextField(blank=True, help_text='Additional handover notes'),
        ),
        migrations.AddField(
            model_name='couponhandover',
            name='last_serial',
            field=models.CharField(blank=True, help_text='Last coupon serial in handover', max_length=50),
        ),
        migrations.AddField(
            model_name='couponhandover',
            name='overrides_entitlement',
            field=models.BooleanField(default=False, help_text='Whether this overrides normal entitlement'),
        ),
        migrations.AddField(
            model_name='couponhandover',
            name='receipt_generated',
            field=models.BooleanField(default=False, help_text='Whether receipt was generated'),
        ),
        migrations.AddField(
            model_name='couponhandover',
            name='received_by',
            field=models.ForeignKey(blank=True, help_text='User who received the coupons', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='couponhandover',
            name='received_date',
            field=models.DateField(blank=True, help_text='Date when received by beneficiary', null=True),
        ),
        migrations.AddField(
            model_name='couponhandover',
            name='received_time',
            field=models.TimeField(blank=True, help_text='Time when received by beneficiary', null=True),
        ),
        migrations.AddField(
            model_name='couponhandover',
            name='representative_id',
            field=models.CharField(blank=True, help_text='Representative ID number', max_length=50),
        ),
        migrations.AddField(
            model_name='couponhandover',
            name='representative_name',
            field=models.CharField(blank=True, help_text='Name of authorized representative', max_length=100),
        ),
        migrations.AddField(
            model_name='couponhandover',
            name='representative_phone',
            field=models.CharField(blank=True, help_text='Representative contact number', max_length=20),
        ),
        migrations.AddField(
            model_name='couponhandover',
            name='representative_signature',
            field=models.TextField(blank=True, help_text='Base64 encoded representative signature'),
        ),
        migrations.AddField(
            model_name='couponhandover',
            name='scheduled_date',
            field=models.DateField(blank=True, help_text='Scheduled handover date', null=True),
        ),
        migrations.AddField(
            model_name='couponhandover',
            name='scheduled_time',
            field=models.TimeField(blank=True, help_text='Scheduled handover time', null=True),
        ),
        migrations.AddField(
            model_name='couponhandover',
            name='special_instructions',
            field=models.TextField(blank=True, help_text='Special handling instructions'),
        ),
        migrations.AddField(
            model_name='couponhandover',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIGURED', 'Configured'), ('VERIFIED', 'Verified'), ('HANDED_OVER', 'Handed Over'), ('RECEIVED', 'Received'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current status of handover', max_length=20),
        ),
        migrations.AddField(
            model_name='couponhandover',
            name='sub_center',
            field=models.ForeignKey(default=django.utils.timezone.now, help_text='Sub-center managing this handover', on_delete=django.db.models.deletion.CASCADE, related_name='coupon_handovers', to='fuel.subcenter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='couponhandover',
            name='total_coupons',
            field=models.IntegerField(default=0, help_text='Total number of coupons in handover'),
        ),
        migrations.AddField(
            model_name='couponhandover',
            name='total_litres',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total litres in handover', max_digits=10),
        ),
        migrations.AddField(
            model_name='couponhandover',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total value of handover in USD', max_digits=12),
        ),
        migrations.AddField(
            model_name='couponhandover',
            name='verification_checks',
            field=models.JSONField(blank=True, default=list, help_text='List of verification checks performed'),
        ),
        migrations.AddField(
            model_name='couponhandover',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Notes from verification process'),
        ),
        migrations.AddField(
            model_name='couponhandover',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='Date and time of verification', null=True),
        ),
        migrations.AddField(
            model_name='couponhandover',
            name='verified_by',
            field=models.CharField(blank=True, help_text='Person who verified the handover', max_length=100),
        ),
        migrations.AddField(
            model_name='couponhandover',
            name='witness_name',
            field=models.CharField(blank=True, help_text='Name of witness', max_length=100),
        ),
        migrations.AddField(
            model_name='couponhandover',
            name='witness_signature',
            field=models.TextField(blank=True, help_text='Base64 encoded witness signature'),
        ),
        migrations.AddField(
            model_name='fuelentitlement',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='User who approved this entitlement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entitlements_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fuelentitlement',
            name='approved_date',
            field=models.DateTimeField(blank=True, help_text='Date when entitlement was approved', null=True),
        ),
        migrations.AddField(
            model_name='fuelentitlement',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this entitlement record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entitlements_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fuelentitlement',
            name='entitlement_type',
            field=models.CharField(choices=[('MONTHLY', 'Monthly Entitlement'), ('SESSION', 'Parliament Session'), ('COMMITTEE', 'Committee Meeting'), ('SPECIAL_EVENT', 'Special Event'), ('TRAVEL_ALLOWANCE', 'Travel Allowance'), ('EMERGENCY', 'Emergency Allocation'), ('CONSTITUENCY_WORK', 'Constituency Work')], default='MONTHLY', help_text='Type of entitlement', max_length=20),
        ),
        migrations.AddField(
            model_name='fuelentitlement',
            name='justification',
            field=models.TextField(blank=True, default='', help_text='Justification for this entitlement'),
        ),
        migrations.AddField(
            model_name='fuelentitlement',
            name='litres_allocated',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount of fuel actually allocated/given', max_digits=8),
        ),
        migrations.AddField(
            model_name='fuelentitlement',
            name='litres_entitled',
            field=models.DecimalField(decimal_places=2, default=200, help_text='Amount of fuel entitled in litres', max_digits=8),
        ),
        migrations.AddField(
            model_name='fuelentitlement',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about this entitlement'),
        ),
        migrations.AddField(
            model_name='fuelentitlement',
            name='period_end',
            field=models.DateField(blank=True, help_text='End date of entitlement period', null=True),
        ),
        migrations.AddField(
            model_name='fuelentitlement',
            name='period_start',
            field=models.DateField(blank=True, help_text='Start date of entitlement period', null=True),
        ),
        migrations.AddField(
            model_name='fuelentitlement',
            name='program',
            field=models.ForeignKey(blank=True, help_text='Related program (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_entitlements', to='fuel.program'),
        ),
        migrations.AddField(
            model_name='fuelentitlement',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Related parliament session (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_entitlements', to='fuel.parliamentsession'),
        ),
        migrations.AddField(
            model_name='fuelentitlement',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('ALLOCATED', 'Allocated'), ('PARTIALLY_ALLOCATED', 'Partially Allocated'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='couponhandover',
            name='beneficiary',
            field=models.ForeignKey(default=django.utils.timezone.now, help_text='Beneficiary receiving the coupons', on_delete=django.db.models.deletion.CASCADE, related_name='coupon_handovers', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
