# Generated by Django 5.2 on 2025-10-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '10037_safe_add_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdispatch',
            name='aggregated_value_zwg',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cached total ZWG value for fast reporting', max_digits=14),
        ),
    ]
